import { Industry, Role, Workflow } from "./types";

export const INDUSTRIES: Industry[] = [
  { slug: "real-estate", name: "Real Estate", description: "Brokers, agents, and property managers" },
  { slug: "insurance", name: "Insurance", description: "Independent agents and brokerages" },
  { slug: "mortgage", name: "Mortgage", description: "Loan officers and brokers" },
  { slug: "legal", name: "Legal", description: "Solo and small law firms" },
  { slug: "dental", name: "Dental", description: "Dental practices and office managers" },
  { slug: "medical", name: "Medical", description: "Private practice and clinics" },
  { slug: "home-services", name: "Home Services", description: "HVAC, plumbing, electrical, roofing, solar" },
  { slug: "aesthetics", name: "Med Spa & Aesthetics", description: "Owners, injectors, and providers" },
  { slug: "financial-advisors", name: "Financial Advisors", description: "Wealth managers and RIAs" },
  { slug: "marketing-agencies", name: "Marketing Agencies", description: "Small to mid-size agencies" },
  { slug: "coaches-consultants", name: "Coaches & Consultants", description: "Solo experts and small firms" },
  { slug: "saas-startups", name: "SaaS & Startups", description: "Founders, ops, and CS teams" },
  { slug: "ecommerce", name: "Ecommerce", description: "DTC brands and Shopify operators" },
  { slug: "education", name: "Education", description: "Tutors, course creators, and schools" },
  { slug: "nonprofits", name: "Nonprofits", description: "Small to mid-size nonprofits" },
  { slug: "other", name: "Other", description: "Tell us your industry" },
];

export const ROLES: Role[] = [
  // Real Estate
  { slug: "real-estate-agent", name: "Real Estate Agent", industrySlug: "real-estate",
    description: "Residential or commercial agent working leads and closing deals",
    searchTerms: ["realtor", "agent", "re agent"] },
  { slug: "real-estate-broker", name: "Real Estate Broker / Owner", industrySlug: "real-estate",
    description: "Brokerage owner managing a team of agents",
    searchTerms: ["broker", "brokerage owner"] },
  { slug: "property-manager", name: "Property Manager", industrySlug: "real-estate",
    description: "Manages residential or commercial rentals",
    searchTerms: ["property mgr", "landlord"] },

  // Insurance
  { slug: "insurance-agent", name: "Insurance Agent", industrySlug: "insurance",
    description: "Independent or captive agent selling personal/commercial lines",
    searchTerms: ["p&c agent", "life agent"] },
  { slug: "insurance-broker", name: "Insurance Broker", industrySlug: "insurance",
    description: "Independent broker placing risk across carriers" },

  // Mortgage
  { slug: "mortgage-loan-officer", name: "Mortgage Loan Officer", industrySlug: "mortgage",
    description: "Originates residential mortgages",
    searchTerms: ["lo", "mlo", "loan officer"] },

  // Legal
  { slug: "solo-attorney", name: "Solo Attorney", industrySlug: "legal",
    description: "Single-shingle lawyer running a small practice" },
  { slug: "personal-injury-attorney", name: "Personal Injury Attorney", industrySlug: "legal",
    description: "PI law firm handling auto, slip-and-fall, and similar cases" },

  // Dental
  { slug: "dental-office-manager", name: "Dental Office Manager", industrySlug: "dental",
    description: "Runs day-to-day operations of a dental practice" },
  { slug: "dentist", name: "Dentist (Owner)", industrySlug: "dental",
    description: "Practice owner balancing chair time and ops" },

  // Medical
  { slug: "private-practice-physician", name: "Private Practice Physician", industrySlug: "medical",
    description: "Solo or small group practice owner" },

  // Home services
  { slug: "hvac-contractor", name: "HVAC Contractor", industrySlug: "home-services",
    description: "Residential HVAC service and install" },
  { slug: "roofing-contractor", name: "Roofing Contractor", industrySlug: "home-services",
    description: "Residential or commercial roofing" },
  { slug: "solar-installer", name: "Solar Installer", industrySlug: "home-services",
    description: "Residential solar sales and install" },

  // Aesthetics
  { slug: "med-spa-owner", name: "Med Spa Owner", industrySlug: "aesthetics",
    description: "Owner-operator of a medical spa or aesthetic clinic" },

  // Financial advisors
  { slug: "financial-advisor", name: "Financial Advisor", industrySlug: "financial-advisors",
    description: "Wealth manager or RIA serving HNW clients" },

  // Marketing agencies
  { slug: "agency-owner", name: "Marketing Agency Owner", industrySlug: "marketing-agencies",
    description: "Owns and runs a small to mid-size agency" },

  // Coaches
  { slug: "coach-consultant", name: "Coach / Consultant", industrySlug: "coaches-consultants",
    description: "Solo expert delivering 1:1 or group programs" },

  // SaaS
  { slug: "saas-founder", name: "SaaS Founder", industrySlug: "saas-startups",
    description: "Early-stage founder wearing every hat" },
  { slug: "customer-success-lead", name: "Customer Success Lead", industrySlug: "saas-startups",
    description: "Runs CS for an early-stage SaaS" },

  // Ecommerce
  { slug: "ecommerce-owner", name: "Ecommerce Owner", industrySlug: "ecommerce",
    description: "DTC brand operator on Shopify or similar" },
];

export const WORKFLOWS: Workflow[] = [
  // ============ REAL ESTATE AGENT ============
  {
    slug: "lead-responder",
    roleSlug: "real-estate-agent",
    name: "Reply to web & Zillow leads in under 2 minutes",
    tagline: "Reply to every Zillow & web lead in under 2 minutes — in your voice.",
    description:
      "Watches Gmail and Zillow inbox 24/7. Drafts personalized first responses in your voice within 90 seconds.",
    longDescription:
      "Most leads go to the agent who replies first. This workflow watches every lead source — Zillow, Realtor.com, your website forms, IDX inquiries — and drafts a personalized first response that sounds like you wrote it. Drafts land in your Gmail Drafts folder. You glance, hit send.",
    category: "Lead gen",
    hoursSavedWeekly: 8,
    dollarsSavedMonthly: 2400,
    rating: 4.9,
    ratingCount: 47,
    setupMinutes: 10,
    requirements: ["Gmail", "Zillow Premier Agent (optional)", "Google Sheets"],
    steps: [
      "Watches your Gmail and Zillow inbox in real time",
      "Detects new lead inquiries using subject patterns + sender filters",
      "Pulls the property address, lead name, and source",
      "Generates a personalized reply using your past responses as voice training",
      "Drops the draft in Gmail Drafts and pings you on Slack",
      "Logs every lead to a Google Sheet for tracking",
    ],
    featured: true,
    source: "Monican",
    priceModel: "monican-setup",
  },
  {
    slug: "past-client-reactivator",
    roleSlug: "real-estate-agent",
    name: "Send personalized weekly check-ins to past clients",
    tagline: "Weekly check-ins with past clients. Birthdays, home anniversaries, market updates.",
    description:
      "Keeps your book of business warm without you remembering anything. Auto-drafts personalized check-in emails every Monday.",
    category: "Past clients",
    hoursSavedWeekly: 4,
    dollarsSavedMonthly: 1800,
    rating: 4.8,
    ratingCount: 32,
    setupMinutes: 15,
    requirements: ["Gmail", "Google Sheets (client list)", "Public records API"],
    steps: [
      "Reads your past client list from Google Sheets",
      "Cross-references birthdays and home-purchase anniversaries",
      "Pulls market data for each client's home address",
      "Generates a custom check-in email for each (3-5 sentences, personal)",
      "Lands every draft in Gmail Monday at 8am",
      "Tracks who opened, replied, or scheduled a call",
    ],
    featured: true,
    source: "Monican",
    priceModel: "monican-setup",
  },
  {
    slug: "signal-engine",
    roleSlug: "real-estate-agent",
    name: "Find listing opportunities from public records",
    tagline: "Spot listing opportunities 60 days before your competition.",
    description:
      "Monitors public records in your farm area for ownership changes, life events, and seller signals.",
    category: "Lead gen",
    hoursSavedWeekly: 6,
    dollarsSavedMonthly: 4500,
    rating: 4.7,
    ratingCount: 28,
    setupMinutes: 20,
    requirements: ["County records access", "Gmail", "Google Sheets"],
    steps: [
      "Scrapes county records weekly for your farm ZIPs",
      "Detects divorce filings, deaths, code violations, expired listings",
      "Scores each signal 1-10 for seller intent",
      "Drafts a tailored outreach letter for the top 30",
      "Delivers a Monday digest with addresses, signals, and draft letters",
      "Auto-archives signals after 90 days",
    ],
    featured: true,
    source: "Monican",
    priceModel: "monican-setup",
  },
  {
    slug: "zillow-lead-to-crm",
    roleSlug: "real-estate-agent",
    name: "Auto-sync Zillow leads into your CRM",
    tagline: "Every Zillow inquiry flows to your CRM in real time, tagged and assigned.",
    description:
      "Zapier-style automation that captures Zillow leads the moment they arrive and routes them to Follow Up Boss, kvCORE, or Sierra Interactive.",
    category: "Lead gen",
    hoursSavedWeekly: 3,
    dollarsSavedMonthly: 800,
    rating: 4.5,
    ratingCount: 412,
    setupMinutes: 5,
    requirements: ["Zillow Premier Agent", "Follow Up Boss / kvCORE / Sierra"],
    steps: [
      "Watches Zillow lead notifications via email parser",
      "Extracts buyer name, property, price range, contact info",
      "Creates lead record in your CRM with proper tags",
      "Triggers your CRM's automation sequence",
      "Sends you a Slack/SMS notification with full lead details",
    ],
    source: "Zapier",
    sourceUrl: "https://zapier.com/apps/zillow/integrations",
    priceModel: "freemium",
  },
  {
    slug: "listing-description-writer",
    roleSlug: "real-estate-agent",
    name: "Generate MLS listing copy from photos & notes",
    tagline: "Turn property notes into Realtor.com-ready listing copy in 30 seconds.",
    description:
      "Paste photos and bullet notes. Get back polished MLS description, social captions, and email blast.",
    category: "Marketing",
    hoursSavedWeekly: 3,
    dollarsSavedMonthly: 600,
    rating: 4.6,
    ratingCount: 1240,
    setupMinutes: 1,
    requirements: ["ChatGPT Plus"],
    steps: [
      "Drop in photos and a few bullet points",
      "GPT generates MLS-compliant description (long + short)",
      "Generates 3 Instagram caption variants",
      "Generates a 'just listed' email blast",
      "Generates a Facebook marketplace post",
      "Exports all copy in one click",
    ],
    source: "GPT Store",
    sourceUrl: "https://chat.openai.com/gpts",
    priceModel: "freemium",
  },
  {
    slug: "open-house-followup",
    roleSlug: "real-estate-agent",
    name: "Personalized follow-up to every open house attendee",
    tagline: "Every attendee gets a personalized thank-you in 24 hours.",
    description:
      "Upload your sign-in sheet. Each attendee gets a personalized email referencing the property.",
    category: "Lead gen",
    hoursSavedWeekly: 2,
    dollarsSavedMonthly: 1200,
    rating: 4.7,
    ratingCount: 22,
    setupMinutes: 8,
    requirements: ["Gmail", "Phone camera"],
    steps: [
      "Snap a photo of your sign-in sheet",
      "OCR extracts names, emails, phone numbers",
      "Each attendee gets a personalized email draft",
      "Drafts reference the property they viewed",
      "Sent within 24 hours (you approve each)",
      "Adds attendees to your past-client CRM",
    ],
    source: "Monican",
    priceModel: "monican-setup",
  },

  // ============ REAL ESTATE BROKER / OWNER ============
  {
    slug: "agent-performance-dashboard",
    roleSlug: "real-estate-broker",
    name: "Weekly digest of every agent&apos;s pipeline & GCI",
    tagline: "See every agent's pipeline, GCI, and activity in one weekly digest.",
    description:
      "Pulls data from your CRM and accounting and emails you a Sunday-night digest of every agent's week.",
    category: "Operations",
    hoursSavedWeekly: 5,
    dollarsSavedMonthly: 2200,
    rating: 4.6,
    ratingCount: 18,
    setupMinutes: 25,
    requirements: ["Brokermint or Sisu", "Gmail"],
    steps: [
      "Pulls deal data from your back-office system",
      "Calculates GCI, units, and activity by agent",
      "Identifies under-performers and stars",
      "Generates a coaching note for each agent",
      "Emails you a digest every Sunday at 6pm",
    ],
    source: "Monican",
    priceModel: "monican-setup",
  },
  {
    slug: "recruiting-bot",
    roleSlug: "real-estate-broker",
    name: "Identify top agents at competitor brokerages weekly",
    tagline: "Identifies top agents at competitor brokerages weekly.",
    description:
      "Monitors MLS for high-volume agents at other brokerages and surfaces them with personalized outreach drafts.",
    category: "Operations",
    hoursSavedWeekly: 6,
    dollarsSavedMonthly: 3500,
    rating: 4.4,
    ratingCount: 9,
    setupMinutes: 30,
    requirements: ["MLS access", "Gmail", "Google Sheets"],
    steps: [
      "Scrapes MLS for agents who closed >5 deals this month at competitor brokerages",
      "Ranks by volume, average price, growth trend",
      "Drafts a personalized recruiting message for each",
      "Delivers weekly digest with one-click email",
    ],
    source: "Monican",
    priceModel: "monican-setup",
  },

  // ============ INSURANCE AGENT ============
  {
    slug: "renewal-outreach",
    roleSlug: "insurance-agent",
    name: "Personal outreach to clients 45 days before renewal",
    tagline: "Personal outreach to every renewing client 45 days before policy end.",
    description:
      "Watches your AMS for upcoming renewals and drafts a personalized check-in email for each — review rates, ask about life changes, suggest cross-sells.",
    longDescription:
      "Renewal retention is 80% of your book's profitability. This workflow surfaces every client whose policy renews in the next 45 days, pulls their current coverage and recent activity, and drafts a tailored email that asks the right questions to prevent churn.",
    category: "Past clients",
    hoursSavedWeekly: 7,
    dollarsSavedMonthly: 3200,
    rating: 4.8,
    ratingCount: 41,
    setupMinutes: 15,
    requirements: ["AMS (Applied/Vertafore/EZLynx)", "Gmail"],
    steps: [
      "Connects to your agency management system",
      "Pulls every policy renewing in 45 days",
      "Drafts personalized check-in email per client",
      "Asks about life changes (marriage, new home, new car)",
      "Suggests cross-sells based on existing coverage gaps",
      "Lands drafts in Gmail every Monday",
    ],
    featured: true,
    source: "Monican",
    priceModel: "monican-setup",
  },
  {
    slug: "quote-followup",
    roleSlug: "insurance-agent",
    name: "Auto follow-up 6 times on every unconverted quote",
    tagline: "Every quote that doesn't close gets 6 personalized touches over 30 days.",
    description:
      "Most quotes die from silence, not rejection. This workflow drips personalized follow-ups to every unconverted quote.",
    category: "Sales",
    hoursSavedWeekly: 4,
    dollarsSavedMonthly: 2800,
    rating: 4.7,
    ratingCount: 56,
    setupMinutes: 10,
    requirements: ["AMS or CRM", "Gmail"],
    steps: [
      "Detects new quote in your AMS or CRM",
      "Schedules a 6-touch follow-up sequence over 30 days",
      "Each touch is personalized to the quote type and customer",
      "Mix of email, SMS, and call reminders",
      "Stops the sequence when prospect responds or buys",
    ],
    source: "Zapier",
    sourceUrl: "https://zapier.com/apps/categories/sales-crm",
    priceModel: "freemium",
  },
  {
    slug: "claims-status-updates",
    roleSlug: "insurance-agent",
    name: "Email clients plain-English claim status updates",
    tagline: "Clients get a status update on their claim without you typing one.",
    description:
      "Watches carrier portals for claim updates and emails the client an explanation in plain English.",
    category: "Operations",
    hoursSavedWeekly: 5,
    dollarsSavedMonthly: 1400,
    rating: 4.6,
    ratingCount: 27,
    setupMinutes: 25,
    requirements: ["Carrier portal access", "Gmail"],
    steps: [
      "Polls carrier portals for claim status changes",
      "Translates insurance-speak into plain English",
      "Drafts a friendly status update to the insured",
      "Includes expected next step and timing",
      "Lands in your Gmail Drafts for approval",
    ],
    source: "n8n",
    sourceUrl: "https://n8n.io/workflows",
    priceModel: "free",
  },
  {
    slug: "x-date-tracker",
    roleSlug: "insurance-agent",
    name: "Track prospect X-dates and outreach 30 days before",
    tagline: "Never miss a competitor's renewal date for a prospect you've quoted.",
    description:
      "Tracks every prospect's X-date and triggers an outreach 30 days before renewal time.",
    category: "Sales",
    hoursSavedWeekly: 3,
    dollarsSavedMonthly: 2100,
    rating: 4.5,
    ratingCount: 19,
    setupMinutes: 15,
    requirements: ["Google Sheets", "Gmail"],
    steps: [
      "Maintains a Google Sheet of prospect X-dates",
      "Sends you a Friday digest of next month's X-dates",
      "Drafts personalized outreach 30 days before each",
      "Logs every touch automatically",
    ],
    source: "Monican",
    priceModel: "monican-setup",
  },

  // ============ MORTGAGE LOAN OFFICER ============
  {
    slug: "rate-watch-alerts",
    roleSlug: "mortgage-loan-officer",
    name: "Email past borrowers when rates drop enough to refi",
    tagline: "When rates drop, your past borrowers get a personalized refi pitch.",
    description:
      "Watches the 30-year fixed rate. When it drops 0.5%+ from a past borrower's locked rate, drafts a personalized refi outreach.",
    category: "Past clients",
    hoursSavedWeekly: 4,
    dollarsSavedMonthly: 5200,
    rating: 4.9,
    ratingCount: 34,
    setupMinutes: 20,
    requirements: ["LOS data export", "Gmail", "FRED API"],
    steps: [
      "Connects to the Freddie Mac rate API",
      "Cross-references your past borrowers' locked rates",
      "Identifies borrowers where refi math works",
      "Drafts a personalized 'rates dropped' email per borrower",
      "Includes payment savings calculation",
      "Lands in Gmail when rates dip",
    ],
    featured: true,
    source: "Monican",
    priceModel: "monican-setup",
  },
  {
    slug: "pre-approval-followup",
    roleSlug: "mortgage-loan-officer",
    name: "Weekly check-ins with pre-approved buyers",
    tagline: "Every pre-approved buyer gets weekly check-ins until they find a home.",
    description:
      "Pre-approvals go cold fast. This workflow keeps you top of mind weekly with market updates and gentle nudges.",
    category: "Sales",
    hoursSavedWeekly: 3,
    dollarsSavedMonthly: 1800,
    rating: 4.6,
    ratingCount: 22,
    setupMinutes: 10,
    requirements: ["Gmail", "Google Sheets"],
    steps: [
      "Tracks every pre-approved buyer with no application",
      "Sends a personalized weekly check-in",
      "Includes local market updates and rate forecasts",
      "Asks specific questions to surface friction",
      "Auto-stops when an application is started",
    ],
    source: "Make",
    sourceUrl: "https://www.make.com/en/templates",
    priceModel: "freemium",
  },
  {
    slug: "realtor-referral-tracker",
    roleSlug: "mortgage-loan-officer",
    name: "Rank and thank Realtor partners by referral volume",
    tagline: "Know which Realtors send you the most volume and reward them.",
    description:
      "Tracks every deal by referring agent. Weekly digest of top referrers + drafted thank-you / co-marketing offers.",
    category: "Operations",
    hoursSavedWeekly: 2,
    dollarsSavedMonthly: 900,
    rating: 4.5,
    ratingCount: 14,
    setupMinutes: 15,
    requirements: ["LOS", "Gmail"],
    steps: [
      "Imports closed deal data from your LOS",
      "Groups by referring real estate agent",
      "Ranks by volume and total GCI",
      "Drafts thank-you and co-marketing offers monthly",
    ],
    source: "Monican",
    priceModel: "monican-setup",
  },

  // ============ SAAS FOUNDER ============
  {
    slug: "weekly-investor-update",
    roleSlug: "saas-founder",
    name: "Draft weekly investor update from your live metrics",
    tagline: "Auto-drafted investor update every Friday from your live metrics.",
    description:
      "Pulls MRR, churn, new logos, and pipeline from Stripe / HubSpot. Drafts a polished investor update email every Friday.",
    longDescription:
      "Investor updates are valuable but tedious. This workflow pulls MRR, churn, NPS, pipeline, and team highlights from your tools and drafts a polished update every Friday. You edit the narrative bits, hit send.",
    category: "Operations",
    hoursSavedWeekly: 3,
    dollarsSavedMonthly: 1500,
    rating: 4.8,
    ratingCount: 89,
    setupMinutes: 30,
    requirements: ["Stripe", "HubSpot or Pipedrive", "Gmail"],
    steps: [
      "Pulls MRR and churn from Stripe",
      "Pulls pipeline from your CRM",
      "Aggregates engineering metrics from GitHub",
      "Drafts the update with a narrative + KPI table",
      "Lands in Gmail Friday morning",
    ],
    featured: true,
    source: "Zapier",
    sourceUrl: "https://zapier.com/apps/integrations",
    priceModel: "freemium",
  },
  {
    slug: "support-triage",
    roleSlug: "saas-founder",
    name: "Categorize, prioritize, and draft every support email",
    tagline: "Every support email gets categorized, prioritized, and drafted in 30 seconds.",
    description:
      "Watches your support inbox. Categorizes (bug / billing / how-to / churn risk). Drafts a response.",
    category: "Operations",
    hoursSavedWeekly: 8,
    dollarsSavedMonthly: 4000,
    rating: 4.7,
    ratingCount: 156,
    setupMinutes: 20,
    requirements: ["Gmail or Intercom", "Anthropic API key"],
    steps: [
      "Polls your support inbox every 60 seconds",
      "Classifies each ticket by type and urgency",
      "Flags churn-risk language for founder review",
      "Drafts a tailored first response",
      "Routes complex cases to a human",
    ],
    featured: true,
    source: "Claude Skills",
    sourceUrl: "https://anthropic.com/claude/skills",
    priceModel: "paid",
  },
  {
    slug: "linkedin-content-engine",
    roleSlug: "saas-founder",
    name: "Draft 5 LinkedIn posts every Sunday from your week",
    tagline: "Post-worthy LinkedIn content from your week, every Sunday.",
    description:
      "Synthesizes your Slack, GitHub commits, and CRM wins into 5 LinkedIn post drafts every Sunday night.",
    category: "Marketing",
    hoursSavedWeekly: 3,
    dollarsSavedMonthly: 1200,
    rating: 4.6,
    ratingCount: 78,
    setupMinutes: 15,
    requirements: ["Slack", "GitHub", "ChatGPT or Claude"],
    steps: [
      "Aggregates your last week's wins from Slack & GitHub",
      "Identifies story-worthy moments",
      "Drafts 5 LinkedIn post variants",
      "Each includes a hook, narrative, and CTA",
      "Lands in your inbox Sunday at 8pm",
    ],
    source: "n8n",
    sourceUrl: "https://n8n.io/workflows",
    priceModel: "free",
  },
  {
    slug: "churn-risk-monitor",
    roleSlug: "saas-founder",
    name: "Get alerted the moment a customer shows churn signals",
    tagline: "Get alerted the moment a customer shows churn signals.",
    description:
      "Watches usage drops, support sentiment, and login frequency. Alerts you to at-risk customers before they cancel.",
    category: "Past clients",
    hoursSavedWeekly: 4,
    dollarsSavedMonthly: 6500,
    rating: 4.8,
    ratingCount: 62,
    setupMinutes: 30,
    requirements: ["Segment or Mixpanel", "Stripe", "Slack"],
    steps: [
      "Tracks per-customer usage trends",
      "Detects 30%+ usage drops or negative support sentiment",
      "Scores each customer's churn risk weekly",
      "Pings you in Slack with at-risk accounts",
      "Drafts a save-the-account outreach for each",
    ],
    source: "Monican",
    priceModel: "monican-setup",
  },
  {
    slug: "inbound-lead-qualifier",
    roleSlug: "saas-founder",
    name: "Qualify, score, and route every demo request in 60s",
    tagline: "Demo requests get qualified, scored, and routed in 60 seconds.",
    description:
      "Every demo request gets enriched, scored ICP fit, and either books on your calendar or gets a polite nurture.",
    category: "Lead gen",
    hoursSavedWeekly: 5,
    dollarsSavedMonthly: 3200,
    rating: 4.7,
    ratingCount: 134,
    setupMinutes: 20,
    requirements: ["Form (Typeform/Tally)", "Clay or Apollo", "Calendar"],
    steps: [
      "Form submission triggers the workflow",
      "Enriches lead with company size, revenue, role",
      "Scores ICP fit 1-10",
      "ICP fit ≥7 → calendar invite",
      "ICP fit <7 → email nurture sequence",
    ],
    source: "Zapier",
    sourceUrl: "https://zapier.com",
    priceModel: "paid",
  },

  // ============ DENTAL OFFICE MANAGER ============
  {
    slug: "patient-recall",
    roleSlug: "dental-office-manager",
    name: "Auto-remind patients due for cleanings via SMS & email",
    tagline: "Every patient due for a cleaning gets a personalized reminder.",
    description:
      "Pulls patients due for 6-month cleanings and sends a personalized recall reminder via email + SMS.",
    category: "Recall",
    hoursSavedWeekly: 6,
    dollarsSavedMonthly: 4800,
    rating: 4.8,
    ratingCount: 41,
    setupMinutes: 25,
    requirements: ["Dentrix / Open Dental / Eaglesoft", "Twilio", "Gmail"],
    steps: [
      "Queries your practice management software for due recalls",
      "Sends a friendly reminder email + SMS",
      "Personalizes with last visit date and provider",
      "Includes one-click booking link",
      "Follows up if no response within 7 days",
    ],
    featured: true,
    source: "Monican",
    priceModel: "monican-setup",
  },
  {
    slug: "no-show-recovery",
    roleSlug: "dental-office-manager",
    name: "Same-day reschedule outreach when a patient no-shows",
    tagline: "Recover 40% of no-shows with same-day outreach.",
    description:
      "When a patient no-shows, an empathetic reschedule message goes out within 2 hours.",
    category: "Recall",
    hoursSavedWeekly: 3,
    dollarsSavedMonthly: 2400,
    rating: 4.6,
    ratingCount: 28,
    setupMinutes: 15,
    requirements: ["Practice management software", "Twilio"],
    steps: [
      "Detects a no-show event",
      "Waits 2 hours then sends a warm reschedule SMS",
      "Offers 3 alternative time slots",
      "Books directly into the system if patient confirms",
    ],
    source: "n8n",
    sourceUrl: "https://n8n.io/workflows",
    priceModel: "free",
  },
  {
    slug: "insurance-verification",
    roleSlug: "dental-office-manager",
    name: "Verify insurance 24h before every appointment",
    tagline: "Insurance verified 24 hours before every appointment.",
    description:
      "Pulls tomorrow's schedule and auto-verifies each patient's insurance coverage so you don't get surprised.",
    category: "Admin",
    hoursSavedWeekly: 8,
    dollarsSavedMonthly: 3600,
    rating: 4.7,
    ratingCount: 52,
    setupMinutes: 30,
    requirements: ["Practice management software", "Insurance verification API"],
    steps: [
      "Pulls tomorrow's appointment list",
      "Queries each patient's insurance benefits",
      "Updates the patient record with current coverage",
      "Flags expired or changed policies",
      "Emails you a morning prep digest",
    ],
    source: "Monican",
    priceModel: "monican-setup",
  },

  // ============ SOLO ATTORNEY ============
  {
    slug: "intake-screener",
    roleSlug: "solo-attorney",
    name: "Filter intake forms and book only viable cases",
    tagline: "Filter the wrong cases before they hit your calendar.",
    description:
      "New intake form responses get analyzed for case viability. Strong cases get a consult booked. Wrong fit gets a polite referral out.",
    category: "Sales",
    hoursSavedWeekly: 5,
    dollarsSavedMonthly: 3800,
    rating: 4.7,
    ratingCount: 38,
    setupMinutes: 20,
    requirements: ["Typeform / Tally", "Gmail", "Calendly"],
    steps: [
      "Intake form submission triggers analysis",
      "Claude evaluates case facts against your criteria",
      "Strong cases → calendar booking link",
      "Weak fits → drafted referral email to a colleague",
      "All intakes logged for review",
    ],
    featured: true,
    source: "Monican",
    priceModel: "monican-setup",
  },
  {
    slug: "court-date-reminders",
    roleSlug: "solo-attorney",
    name: "Multi-channel reminders for every filing & court date",
    tagline: "Never miss a filing deadline or court date again.",
    description:
      "Watches your case management system and sends multi-channel reminders for upcoming deadlines.",
    category: "Compliance",
    hoursSavedWeekly: 3,
    dollarsSavedMonthly: 2200,
    rating: 4.9,
    ratingCount: 24,
    setupMinutes: 15,
    requirements: ["Clio / MyCase / PracticePanther"],
    steps: [
      "Syncs every case deadline weekly",
      "Sends you reminders 7 days, 3 days, 1 day out",
      "Notifies the client of upcoming court appearances",
      "Drafts last-minute filing reminders for staff",
    ],
    source: "Zapier",
    sourceUrl: "https://zapier.com/apps/clio",
    priceModel: "freemium",
  },
  {
    slug: "contract-review",
    roleSlug: "solo-attorney",
    name: "Spot 10 red flags in any contract in 60 seconds",
    tagline: "Spot the 10 most common red flags in any contract in 60 seconds.",
    description:
      "Drop a PDF contract. Get back a 1-page summary, key risks, missing clauses, and suggested redlines.",
    category: "Admin",
    hoursSavedWeekly: 6,
    dollarsSavedMonthly: 4400,
    rating: 4.6,
    ratingCount: 167,
    setupMinutes: 2,
    requirements: ["ChatGPT Plus or Claude"],
    steps: [
      "Drop a contract PDF",
      "Claude generates a 1-page executive summary",
      "Identifies missing standard clauses",
      "Flags 10 most common red flags",
      "Suggests specific redline language",
    ],
    source: "Claude Skills",
    sourceUrl: "https://anthropic.com/claude/skills",
    priceModel: "paid",
  },

  // ============ AGENCY OWNER ============
  {
    slug: "weekly-client-reports",
    roleSlug: "agency-owner",
    name: "Generate personalized client reports every Monday",
    tagline: "Every client gets a polished performance report every Monday — no manual work.",
    description:
      "Pulls data from GA4, Meta Ads, Google Ads, and Search Console. Drafts a personalized weekly report per client.",
    category: "Operations",
    hoursSavedWeekly: 10,
    dollarsSavedMonthly: 4800,
    rating: 4.7,
    ratingCount: 92,
    setupMinutes: 30,
    requirements: ["GA4", "Meta Ads", "Google Ads", "Slack"],
    steps: [
      "Pulls last week's data from all platforms",
      "Generates KPIs and YoY comparisons",
      "Drafts a personalized narrative per client",
      "Exports as branded PDF",
      "Lands in your inbox Monday at 7am",
    ],
    featured: true,
    source: "Make",
    sourceUrl: "https://make.com/templates",
    priceModel: "freemium",
  },
  {
    slug: "proposal-generator",
    roleSlug: "agency-owner",
    name: "Turn discovery notes into a branded proposal",
    tagline: "Turn discovery call notes into a branded proposal in 5 minutes.",
    description:
      "Paste your discovery call notes. Get back a fully-formatted proposal with scope, timeline, and pricing.",
    category: "Sales",
    hoursSavedWeekly: 5,
    dollarsSavedMonthly: 3200,
    rating: 4.6,
    ratingCount: 47,
    setupMinutes: 10,
    requirements: ["Google Docs", "Claude or ChatGPT"],
    steps: [
      "Paste discovery call notes",
      "AI generates project scope and deliverables",
      "Pulls pricing from your template",
      "Outputs a branded Google Doc",
      "Includes case studies relevant to the client's industry",
    ],
    source: "GPT Store",
    sourceUrl: "https://chat.openai.com/gpts",
    priceModel: "freemium",
  },

  // ============ COACH / CONSULTANT ============
  {
    slug: "client-session-prep",
    roleSlug: "coach-consultant",
    name: "Auto-brief before every coaching session",
    tagline: "10-minute prep for every coaching session, done before you sit down.",
    description:
      "Pulls last session's notes, recent client emails, and progress against goals. Generates a 1-page brief before each call.",
    category: "Operations",
    hoursSavedWeekly: 4,
    dollarsSavedMonthly: 1600,
    rating: 4.8,
    ratingCount: 73,
    setupMinutes: 15,
    requirements: ["Gmail", "Notion or Google Docs"],
    steps: [
      "Reads your client's last session notes",
      "Scans their recent emails to you",
      "Pulls active goals and pending action items",
      "Generates a 1-page brief 1 hour before each session",
      "Delivers via email or Slack",
    ],
    featured: true,
    source: "Monican",
    priceModel: "monican-setup",
  },
  {
    slug: "content-repurposing",
    roleSlug: "coach-consultant",
    name: "Turn one podcast into 12 pieces of content",
    tagline: "Turn one podcast episode into 12 pieces of content.",
    description:
      "Record once. Get back a blog post, LinkedIn carousel, Twitter thread, Instagram captions, and YouTube chapters.",
    category: "Marketing",
    hoursSavedWeekly: 6,
    dollarsSavedMonthly: 2400,
    rating: 4.7,
    ratingCount: 248,
    setupMinutes: 5,
    requirements: ["Descript or Otter", "Claude or ChatGPT"],
    steps: [
      "Drop a podcast or video transcript",
      "AI extracts the top 5 insights",
      "Generates a 1000-word blog post",
      "Creates a 10-slide LinkedIn carousel",
      "Drafts a Twitter thread",
      "Generates 5 Instagram captions",
    ],
    source: "GPT Store",
    sourceUrl: "https://chat.openai.com/gpts",
    priceModel: "freemium",
  },

  // ============ MED SPA OWNER ============
  {
    slug: "follow-up-treatment-protocol",
    roleSlug: "med-spa-owner",
    name: "Auto check-in 48h and 2 weeks after every treatment",
    tagline: "Every patient gets a personalized check-in 48 hours and 2 weeks post-treatment.",
    description:
      "Automatic check-ins after injectables, lasers, or facials. Builds loyalty and surfaces complications early.",
    category: "Recall",
    hoursSavedWeekly: 4,
    dollarsSavedMonthly: 3200,
    rating: 4.8,
    ratingCount: 64,
    setupMinutes: 20,
    requirements: ["PMS (Boulevard/Vagaro)", "Twilio"],
    steps: [
      "Watches for completed treatments",
      "Sends 48-hour check-in SMS asking about results",
      "Sends 2-week follow-up with rebooking link",
      "Flags any negative responses for owner review",
      "Tracks NPS over time",
    ],
    featured: true,
    source: "Monican",
    priceModel: "monican-setup",
  },
];

// Helpers
export function getIndustryBySlug(slug: string): Industry | undefined {
  return INDUSTRIES.find((i) => i.slug === slug);
}

export function getRoleBySlug(slug: string): Role | undefined {
  return ROLES.find((r) => r.slug === slug);
}

export function getRolesByIndustry(industrySlug: string): Role[] {
  return ROLES.filter((r) => r.industrySlug === industrySlug);
}

export function getWorkflowsForRole(roleSlug: string): Workflow[] {
  return WORKFLOWS.filter((w) => w.roleSlug === roleSlug);
}

export function getWorkflow(roleSlug: string, workflowSlug: string): Workflow | undefined {
  return WORKFLOWS.find((w) => w.roleSlug === roleSlug && w.slug === workflowSlug);
}
