import { Industry, Role, Workflow } from "./types";

export const INDUSTRIES: Industry[] = [
  { slug: "real-estate", name: "Real Estate", description: "Brokers, agents, and property managers" },
  { slug: "insurance", name: "Insurance", description: "Independent agents and brokerages" },
  { slug: "mortgage", name: "Mortgage", description: "Loan officers and brokers" },
  { slug: "legal", name: "Legal", description: "Solo and small law firms" },
  { slug: "dental", name: "Dental", description: "Dental practices and office managers" },
  { slug: "medical", name: "Medical", description: "Private practice and clinics" },
  { slug: "home-services", name: "Home Services", description: "HVAC, plumbing, electrical, roofing, solar" },
  { slug: "aesthetics", name: "Med Spa & Aesthetics", description: "Owners, injectors, and providers" },
  { slug: "financial-advisors", name: "Financial Advisors", description: "Wealth managers and RIAs" },
  { slug: "marketing-agencies", name: "Marketing Agencies", description: "Small to mid-size agencies" },
  { slug: "coaches-consultants", name: "Coaches & Consultants", description: "Solo experts and small firms" },
  { slug: "saas-startups", name: "SaaS & Startups", description: "Founders, ops, and CS teams" },
  { slug: "ecommerce", name: "Ecommerce", description: "DTC brands and Shopify operators" },
  { slug: "education", name: "Education", description: "Tutors, course creators, and schools" },
  { slug: "nonprofits", name: "Nonprofits", description: "Small to mid-size nonprofits" },
  { slug: "accounting", name: "Accounting & Bookkeeping", description: "CPAs, bookkeepers, and tax pros" },
  { slug: "restaurants", name: "Restaurants & Hospitality", description: "Restaurant and hotel owners" },
  { slug: "construction", name: "Construction", description: "GCs, builders, and remodelers" },
  { slug: "automotive", name: "Automotive", description: "Auto repair, dealerships, body shops" },
  { slug: "veterinary", name: "Veterinary", description: "Vet practice owners and managers" },
  { slug: "fitness", name: "Fitness & Wellness", description: "Gym, studio, and trainer owners" },
  { slug: "salons", name: "Salons & Beauty", description: "Hair salon, nail salon, barber shop owners" },
  { slug: "mental-health", name: "Mental Health & Therapy", description: "Therapists, psychologists, group practices" },
  { slug: "recruiting", name: "Recruiting & Staffing", description: "Agency owners and recruiters" },
  { slug: "creative", name: "Photography & Creative", description: "Photographers, videographers, designers" },
  { slug: "investing", name: "Property Investing", description: "Flippers, wholesalers, REI operators" },
  { slug: "childcare", name: "Childcare & Daycare", description: "Daycare owners, preschool operators" },
  { slug: "cleaning", name: "Cleaning Services", description: "Residential and commercial cleaning" },
  { slug: "landscaping", name: "Landscaping", description: "Lawn care and landscape design" },
  { slug: "pet-care", name: "Pet Care", description: "Grooming, daycare, dog walking, boarding" },
  { slug: "manufacturing", name: "Manufacturing", description: "Small manufacturers and job shops" },
  { slug: "logistics", name: "Logistics & Freight", description: "Trucking, freight brokers, 3PL" },
  { slug: "events", name: "Events & Weddings", description: "Planners, venues, caterers" },
  { slug: "travel", name: "Travel & Tour Operators", description: "Travel agents, tour operators" },
  { slug: "media", name: "Media & Content Creators", description: "Podcasters, newsletter writers, YouTubers" },
  { slug: "religious", name: "Religious Organizations", description: "Churches, synagogues, temples" },
  { slug: "other", name: "Other", description: "Tell us your industry" },
];

export const ROLES: Role[] = [
  { slug: "real-estate-agent", name: "Real Estate Agent", industrySlug: "real-estate",
    description: "Residential or commercial agent working leads and closing deals",
    searchTerms: ["realtor", "agent", "re agent"] },
  { slug: "real-estate-broker", name: "Real Estate Broker / Owner", industrySlug: "real-estate",
    description: "Brokerage owner managing a team of agents",
    searchTerms: ["broker", "brokerage owner"] },
  { slug: "property-manager", name: "Property Manager", industrySlug: "real-estate",
    description: "Manages residential or commercial rentals",
    searchTerms: ["property mgr", "landlord"] },
  { slug: "insurance-agent", name: "Insurance Agent", industrySlug: "insurance",
    description: "Independent or captive agent selling personal/commercial lines",
    searchTerms: ["p&c agent", "life agent"] },
  { slug: "insurance-broker", name: "Insurance Broker", industrySlug: "insurance",
    description: "Independent broker placing risk across carriers" },
  { slug: "mortgage-loan-officer", name: "Mortgage Loan Officer", industrySlug: "mortgage",
    description: "Originates residential mortgages",
    searchTerms: ["lo", "mlo", "loan officer"] },
  { slug: "solo-attorney", name: "Solo Attorney", industrySlug: "legal",
    description: "Single-shingle lawyer running a small practice" },
  { slug: "personal-injury-attorney", name: "Personal Injury Attorney", industrySlug: "legal",
    description: "PI law firm handling auto, slip-and-fall, and similar cases" },
  { slug: "dental-office-manager", name: "Dental Office Manager", industrySlug: "dental",
    description: "Runs day-to-day operations of a dental practice" },
  { slug: "dentist", name: "Dentist (Owner)", industrySlug: "dental",
    description: "Practice owner balancing chair time and ops" },
  { slug: "private-practice-physician", name: "Private Practice Physician", industrySlug: "medical",
    description: "Solo or small group practice owner" },
  { slug: "hvac-contractor", name: "HVAC Contractor", industrySlug: "home-services",
    description: "Residential HVAC service and install" },
  { slug: "roofing-contractor", name: "Roofing Contractor", industrySlug: "home-services",
    description: "Residential or commercial roofing" },
  { slug: "solar-installer", name: "Solar Installer", industrySlug: "home-services",
    description: "Residential solar sales and install" },
  { slug: "med-spa-owner", name: "Med Spa Owner", industrySlug: "aesthetics",
    description: "Owner-operator of a medical spa or aesthetic clinic" },
  { slug: "financial-advisor", name: "Financial Advisor", industrySlug: "financial-advisors",
    description: "Wealth manager or RIA serving HNW clients" },
  { slug: "agency-owner", name: "Marketing Agency Owner", industrySlug: "marketing-agencies",
    description: "Owns and runs a small to mid-size agency" },
  { slug: "coach-consultant", name: "Coach / Consultant", industrySlug: "coaches-consultants",
    description: "Solo expert delivering 1:1 or group programs" },
  { slug: "saas-founder", name: "SaaS Founder", industrySlug: "saas-startups",
    description: "Early-stage founder wearing every hat" },
  { slug: "customer-success-lead", name: "Customer Success Lead", industrySlug: "saas-startups",
    description: "Runs CS for an early-stage SaaS" },
  { slug: "ecommerce-owner", name: "Ecommerce Owner", industrySlug: "ecommerce",
    description: "DTC brand operator on Shopify or similar" },

  // Accounting & Bookkeeping
  { slug: "solo-cpa", name: "Solo CPA", industrySlug: "accounting",
    description: "Solo certified public accountant", searchTerms: ["cpa", "accountant", "tax prep"] },
  { slug: "bookkeeper", name: "Bookkeeper", industrySlug: "accounting",
    description: "Small business bookkeeper", searchTerms: ["bookkeeping", "books"] },
  { slug: "tax-preparer", name: "Tax Preparer", industrySlug: "accounting",
    description: "Tax prep professional or EA", searchTerms: ["taxes", "ea", "enrolled agent"] },

  // Restaurants & Hospitality
  { slug: "restaurant-owner", name: "Restaurant Owner", industrySlug: "restaurants",
    description: "Independent restaurant operator", searchTerms: ["restaurant", "cafe", "bar"] },
  { slug: "hotel-owner", name: "Hotel / B&B Owner", industrySlug: "restaurants",
    description: "Boutique hotel or bed and breakfast", searchTerms: ["hotel", "inn", "b&b"] },
  { slug: "catering-owner", name: "Catering Business Owner", industrySlug: "restaurants",
    description: "Catering company operator", searchTerms: ["catering", "caterer"] },

  // Construction
  { slug: "general-contractor", name: "General Contractor", industrySlug: "construction",
    description: "Residential or commercial GC", searchTerms: ["gc", "contractor", "builder"] },
  { slug: "remodeler", name: "Remodeler", industrySlug: "construction",
    description: "Kitchen, bath, and whole-home remodeling" },
  { slug: "custom-home-builder", name: "Custom Home Builder", industrySlug: "construction",
    description: "Builds custom residential homes", searchTerms: ["builder"] },

  // Automotive
  { slug: "auto-repair-owner", name: "Auto Repair Shop Owner", industrySlug: "automotive",
    description: "Independent auto repair shop", searchTerms: ["mechanic", "auto shop", "garage"] },
  { slug: "dealership-manager", name: "Dealership Manager", industrySlug: "automotive",
    description: "New or used car dealership operations" },
  { slug: "body-shop-owner", name: "Body Shop Owner", industrySlug: "automotive",
    description: "Collision repair shop owner", searchTerms: ["collision"] },

  // Veterinary
  { slug: "vet-owner", name: "Veterinarian (Owner)", industrySlug: "veterinary",
    description: "Practice owner DVM", searchTerms: ["dvm", "veterinarian", "vet"] },
  { slug: "vet-practice-manager", name: "Vet Practice Manager", industrySlug: "veterinary",
    description: "Operations manager for vet practice" },

  // Fitness & Wellness
  { slug: "gym-owner", name: "Gym Owner", industrySlug: "fitness",
    description: "Independent gym or studio owner", searchTerms: ["gym", "fitness studio"] },
  { slug: "personal-trainer", name: "Personal Trainer", industrySlug: "fitness",
    description: "Solo personal trainer or coach", searchTerms: ["trainer", "coach"] },
  { slug: "yoga-studio-owner", name: "Yoga / Pilates Studio Owner", industrySlug: "fitness",
    description: "Boutique fitness studio operator" },
  { slug: "nutritionist", name: "Nutritionist / Dietitian", industrySlug: "fitness",
    description: "Private practice nutrition coach", searchTerms: ["dietitian", "rd"] },

  // Salons & Beauty
  { slug: "salon-owner", name: "Salon Owner", industrySlug: "salons",
    description: "Hair salon or barbershop owner", searchTerms: ["hair", "barber"] },
  { slug: "stylist", name: "Independent Stylist", industrySlug: "salons",
    description: "Booth-rent or chair-rent stylist", searchTerms: ["hairdresser"] },
  { slug: "nail-salon-owner", name: "Nail Salon Owner", industrySlug: "salons",
    description: "Nail salon operator" },

  // Mental Health
  { slug: "solo-therapist", name: "Solo Therapist", industrySlug: "mental-health",
    description: "Private practice therapist (LCSW, LPC, etc.)", searchTerms: ["therapist", "counselor", "lcsw"] },
  { slug: "psychologist", name: "Psychologist", industrySlug: "mental-health",
    description: "Private practice psychologist", searchTerms: ["psychologist", "psyd", "phd"] },
  { slug: "therapy-group-practice", name: "Therapy Group Practice Owner", industrySlug: "mental-health",
    description: "Owner of multi-clinician practice" },

  // Recruiting & Staffing
  { slug: "recruiter", name: "Recruiter", industrySlug: "recruiting",
    description: "Independent recruiter or sourcer", searchTerms: ["headhunter", "sourcer"] },
  { slug: "staffing-agency-owner", name: "Staffing Agency Owner", industrySlug: "recruiting",
    description: "Owner of a staffing or recruiting agency" },

  // Photography & Creative
  { slug: "wedding-photographer", name: "Wedding Photographer", industrySlug: "creative",
    description: "Solo or studio wedding photographer", searchTerms: ["photographer"] },
  { slug: "videographer", name: "Videographer", industrySlug: "creative",
    description: "Freelance or studio videographer", searchTerms: ["video", "filmmaker"] },
  { slug: "freelance-designer", name: "Freelance Designer", industrySlug: "creative",
    description: "Solo graphic, brand, or web designer", searchTerms: ["designer", "graphic design"] },

  // Property Investing
  { slug: "house-flipper", name: "House Flipper", industrySlug: "investing",
    description: "Buy-and-flip real estate operator", searchTerms: ["flipper", "rehab"] },
  { slug: "wholesaler", name: "Real Estate Wholesaler", industrySlug: "investing",
    description: "Contract assignment wholesaler", searchTerms: ["wholesaler"] },
  { slug: "rei-fund-operator", name: "REI Fund Operator", industrySlug: "investing",
    description: "Multifamily or fund operator", searchTerms: ["syndicator", "multifamily"] },

  // Childcare
  { slug: "daycare-owner", name: "Daycare Owner", industrySlug: "childcare",
    description: "Licensed daycare center operator", searchTerms: ["daycare", "childcare"] },
  { slug: "preschool-director", name: "Preschool Director", industrySlug: "childcare",
    description: "Private preschool director" },

  // Cleaning
  { slug: "residential-cleaning-owner", name: "Residential Cleaning Owner", industrySlug: "cleaning",
    description: "Maid service or house cleaning company", searchTerms: ["cleaning", "maid"] },
  { slug: "commercial-cleaning-owner", name: "Commercial Cleaning Owner", industrySlug: "cleaning",
    description: "Janitorial or office cleaning service", searchTerms: ["janitorial"] },

  // Landscaping
  { slug: "landscaper", name: "Landscaper / Lawn Care Owner", industrySlug: "landscaping",
    description: "Residential lawn care or landscape company", searchTerms: ["lawn care", "landscape"] },
  { slug: "tree-service-owner", name: "Tree Service Owner", industrySlug: "landscaping",
    description: "Arborist or tree removal company" },

  // Pet Care
  { slug: "groomer", name: "Pet Groomer", industrySlug: "pet-care",
    description: "Mobile or shop-based pet groomer", searchTerms: ["groomer"] },
  { slug: "dog-walker", name: "Dog Walker / Pet Sitter", industrySlug: "pet-care",
    description: "Solo or team-based pet care" },
  { slug: "boarding-owner", name: "Boarding Facility Owner", industrySlug: "pet-care",
    description: "Pet boarding or daycare facility" },

  // Manufacturing
  { slug: "small-manufacturer", name: "Small Manufacturer", industrySlug: "manufacturing",
    description: "Owner of small manufacturing or job shop" },

  // Logistics
  { slug: "trucking-owner", name: "Trucking Company Owner", industrySlug: "logistics",
    description: "Small trucking fleet owner", searchTerms: ["trucker", "freight"] },
  { slug: "freight-broker", name: "Freight Broker", industrySlug: "logistics",
    description: "Independent freight broker or 3PL" },

  // Events
  { slug: "wedding-planner", name: "Wedding Planner", industrySlug: "events",
    description: "Solo or small-team wedding planner" },
  { slug: "event-venue-owner", name: "Event Venue Owner", industrySlug: "events",
    description: "Venue or banquet hall operator" },

  // Travel
  { slug: "travel-agent", name: "Travel Agent", industrySlug: "travel",
    description: "Independent travel agent or advisor", searchTerms: ["travel advisor"] },
  { slug: "tour-operator", name: "Tour Operator", industrySlug: "travel",
    description: "Custom or group tour operator" },

  // Media & Creators
  { slug: "podcaster", name: "Podcaster", industrySlug: "media",
    description: "Independent podcast creator", searchTerms: ["podcast"] },
  { slug: "newsletter-writer", name: "Newsletter Writer", industrySlug: "media",
    description: "Substack or newsletter operator", searchTerms: ["substack", "newsletter"] },
  { slug: "youtuber", name: "YouTuber / Creator", industrySlug: "media",
    description: "Full-time content creator", searchTerms: ["creator", "youtube"] },

  // Religious orgs
  { slug: "pastor", name: "Pastor / Faith Leader", industrySlug: "religious",
    description: "Pastor or leader of a religious organization", searchTerms: ["pastor", "rabbi", "imam"] },

  // Education (was empty)
  { slug: "tutor", name: "Tutor", industrySlug: "education",
    description: "Solo subject tutor or test prep", searchTerms: ["tutor"] },
  { slug: "course-creator", name: "Course Creator", industrySlug: "education",
    description: "Online course or membership operator", searchTerms: ["course", "membership"] },
  { slug: "private-school-admin", name: "Private School Admin", industrySlug: "education",
    description: "Admissions, ops, or principal" },

  // Nonprofits (was empty)
  { slug: "nonprofit-ed", name: "Nonprofit Executive Director", industrySlug: "nonprofits",
    description: "ED of small to mid-size nonprofit", searchTerms: ["nonprofit", "ed"] },
  { slug: "fundraiser", name: "Fundraiser / Development Officer", industrySlug: "nonprofits",
    description: "Major gifts or development officer" },
];

// Helper to keep new workflows compact
const wf = (w: Workflow): Workflow => w;

export const WORKFLOWS: Workflow[] = [
  // ============ REAL ESTATE AGENT ============
  wf({
    slug: "lead-responder", roleSlug: "real-estate-agent",
    name: "Reply to web & Zillow leads in under 2 minutes",
    tagline: "Reply in your voice, in under 2 minutes.",
    description: "Watches Gmail and Zillow inbox 24/7. Drafts personalized first responses within 90 seconds.",
    category: "Lead gen",
    timePerAction: "Saves 6 min per lead reply",
    hoursSavedWeekly: 8, dollarsSavedMonthly: 2400, rating: 4.9, ratingCount: 47, setupMinutes: 10,
    requirements: ["Gmail", "Zillow", "Google Sheets"],
    steps: [
      "Watches Gmail and Zillow inbox in real time",
      "Extracts lead name, property, source",
      "Drafts personalized reply trained on your voice",
      "Lands draft in Gmail + Slack ping",
    ],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "past-client-reactivator", roleSlug: "real-estate-agent",
    name: "Send personalized weekly check-ins to past clients",
    tagline: "Keep your book of business warm.",
    description: "Auto-drafts personalized check-in emails every Monday based on birthdays, anniversaries, and market changes.",
    category: "Past clients",
    timePerAction: "Saves 4 min per client touch",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 1800, rating: 4.8, ratingCount: 32, setupMinutes: 15,
    requirements: ["Gmail", "Google Sheets", "Public records API"],
    steps: ["Reads client list from Sheets", "Cross-references birthdays + anniversaries", "Drafts personalized email per client", "Lands in Gmail Monday 8am"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "signal-engine", roleSlug: "real-estate-agent",
    name: "Find listing opportunities from public records",
    tagline: "Spot sellers 60 days before your competition.",
    description: "Monitors public records in your farm for divorces, deaths, code violations, and other seller signals.",
    category: "Lead gen",
    timePerAction: "Saves 28 min per qualified signal",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 4500, rating: 4.7, ratingCount: 28, setupMinutes: 20,
    requirements: ["County records", "Gmail", "Google Sheets"],
    steps: ["Scrapes county records weekly", "Scores each signal 1-10", "Drafts outreach for top 30", "Weekly Monday digest"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "zillow-lead-to-crm", roleSlug: "real-estate-agent",
    name: "Auto-sync Zillow leads into your CRM",
    tagline: "Zillow → CRM in real time.",
    description: "Captures Zillow leads the moment they arrive and routes them to Follow Up Boss, kvCORE, or Sierra Interactive.",
    category: "Lead gen",
    timePerAction: "Saves 3 min per lead entry",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 800, rating: 4.5, ratingCount: 412, setupMinutes: 5,
    requirements: ["Zillow", "Follow Up Boss / kvCORE"],
    steps: ["Parses Zillow lead emails", "Creates CRM record with tags", "Triggers automation sequence", "Slack/SMS notification"],
    source: "Zapier", sourceUrl: "https://zapier.com/apps/zillow/integrations", priceModel: "freemium",
  }),
  wf({
    slug: "listing-description-writer", roleSlug: "real-estate-agent",
    name: "Generate MLS listing copy from photos & notes",
    tagline: "Polished listing copy in 30 seconds.",
    description: "Drop photos and bullet notes. Get MLS description, social captions, and email blast back.",
    category: "Marketing",
    timePerAction: "Saves 18 min per listing",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 600, rating: 4.6, ratingCount: 1240, setupMinutes: 1,
    requirements: ["ChatGPT Plus"],
    steps: ["Drop photos + bullet points", "Generates MLS long + short copy", "Creates 3 social captions", "Exports in one click"],
    source: "GPT Store", sourceUrl: "https://chat.openai.com/gpts", priceModel: "freemium",
  }),
  wf({
    slug: "open-house-followup", roleSlug: "real-estate-agent",
    name: "Personalized follow-up to every open house attendee",
    tagline: "24-hour follow-up to every sign-in.",
    description: "Upload your sign-in sheet. Each attendee gets a personalized email referencing the property.",
    category: "Lead gen",
    timePerAction: "Saves 2.5 min per attendee",
    hoursSavedWeekly: 2, dollarsSavedMonthly: 1200, rating: 4.7, ratingCount: 22, setupMinutes: 8,
    requirements: ["Gmail", "Phone camera"],
    steps: ["Snap sign-in sheet photo", "OCR extracts contacts", "Draft personalized email per attendee", "Approve and send"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ REAL ESTATE BROKER / OWNER ============
  wf({
    slug: "agent-performance-digest", roleSlug: "real-estate-broker",
    name: "Weekly digest of every agent's pipeline & GCI",
    tagline: "One-glance view of every agent every Sunday.",
    description: "Pulls deal data from Brokermint or Sisu and emails you a Sunday digest of every agent's week.",
    category: "Operations",
    timePerAction: "Saves 12 min per agent review",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 2200, rating: 4.6, ratingCount: 18, setupMinutes: 25,
    requirements: ["Brokermint", "Gmail"],
    steps: ["Pulls deal data weekly", "Calculates GCI per agent", "Flags under-performers", "Sunday 6pm email"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "recruiting-bot", roleSlug: "real-estate-broker",
    name: "Identify top agents at competitor brokerages weekly",
    tagline: "Recruit from competitors based on real MLS data.",
    description: "Monitors MLS for high-volume agents at other brokerages with personalized outreach drafts.",
    category: "Operations",
    timePerAction: "Saves 20 min per recruit identified",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 3500, rating: 4.4, ratingCount: 9, setupMinutes: 30,
    requirements: ["MLS access", "Gmail"],
    steps: ["Scrapes MLS weekly", "Ranks by volume + price", "Drafts personalized recruiting messages", "Weekly digest delivery"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "broker-comp-tracker", roleSlug: "real-estate-broker",
    name: "Track and pay agent commissions automatically",
    tagline: "End-of-month commission runs in 10 minutes flat.",
    description: "Reads closed deals, calculates splits per agent, generates commission disbursement summary.",
    category: "Admin",
    timePerAction: "Saves 7 min per commission calc",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 1800, rating: 4.5, ratingCount: 11, setupMinutes: 20,
    requirements: ["Brokermint", "QuickBooks"],
    steps: ["Pulls closings monthly", "Calculates split per agent", "Generates DA reports", "Pushes to QuickBooks"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "compliance-doc-checker", roleSlug: "real-estate-broker",
    name: "Auto-check every file for missing compliance docs",
    tagline: "Catch missing forms before the state does.",
    description: "Watches transaction files and flags missing disclosures, signatures, or required addenda.",
    category: "Compliance",
    timePerAction: "Saves 8 min per file review",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 1500, rating: 4.7, ratingCount: 14, setupMinutes: 25,
    requirements: ["Dotloop / SkySlope", "Slack"],
    steps: ["Watches new transactions", "Cross-checks state-required docs", "Pings agent in Slack", "Weekly compliance report"],
    source: "n8n", sourceUrl: "https://n8n.io/workflows", priceModel: "free",
  }),

  // ============ PROPERTY MANAGER ============
  wf({
    slug: "tenant-screening", roleSlug: "property-manager",
    name: "Auto-screen tenant applications in 60 seconds",
    tagline: "Credit, criminal, and rental history in one report.",
    description: "Pulls credit, criminal, and rental history reports the moment an application is submitted.",
    category: "Admin",
    timePerAction: "Saves 22 min per applicant",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 1800, rating: 4.7, ratingCount: 38, setupMinutes: 15,
    requirements: ["TransUnion SmartMove", "Gmail"],
    steps: ["Triggered by new application", "Pulls credit + criminal + eviction history", "Scores applicant 1-10", "Emails summary to you"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "maintenance-ticket-router", roleSlug: "property-manager",
    name: "Triage maintenance requests and dispatch vendors",
    tagline: "From tenant text to vendor on-site in under an hour.",
    description: "Classifies maintenance tickets by urgency, routes to the right vendor, and updates the tenant.",
    category: "Operations",
    timePerAction: "Saves 14 min per ticket",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 2400, rating: 4.8, ratingCount: 56, setupMinutes: 20,
    requirements: ["AppFolio", "Twilio", "Vendor list"],
    steps: ["Watches incoming maintenance requests", "Classifies urgency (emergency / routine)", "Dispatches matching vendor", "Updates tenant with ETA"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "rent-collection", roleSlug: "property-manager",
    name: "Automated rent reminders and late-fee handling",
    tagline: "Polite reminders that get rent paid 4 days faster.",
    description: "Sends rent reminders 5 days before, on due date, and after. Auto-applies late fees per lease terms.",
    category: "Operations",
    timePerAction: "Saves 3 min per tenant per month",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 1600, rating: 4.6, ratingCount: 41, setupMinutes: 10,
    requirements: ["Buildium / AppFolio", "Twilio"],
    steps: ["Watches due dates per lease", "Sends reminders via SMS + email", "Auto-applies late fees", "Updates ledger"],
    source: "Zapier", sourceUrl: "https://zapier.com", priceModel: "freemium",
  }),
  wf({
    slug: "lease-renewal-engine", roleSlug: "property-manager",
    name: "Auto-draft lease renewals 90 days before expiration",
    tagline: "Renew without scrambling at the last minute.",
    description: "Watches every lease and 90 days out drafts a renewal offer with comp-based pricing.",
    category: "Past clients",
    timePerAction: "Saves 15 min per renewal",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 2200, rating: 4.7, ratingCount: 22, setupMinutes: 20,
    requirements: ["Buildium", "Rent comparison API"],
    steps: ["Pulls leases expiring in 90 days", "Researches local rent comps", "Drafts renewal offer with price", "Emails tenant + you for approval"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ INSURANCE AGENT ============
  wf({
    slug: "renewal-outreach", roleSlug: "insurance-agent",
    name: "Personal outreach to clients 45 days before renewal",
    tagline: "Renewal retention without manual prep.",
    description: "Watches your AMS for upcoming renewals. Drafts personalized check-in for each — review rates, ask about life changes, suggest cross-sells.",
    category: "Past clients",
    timePerAction: "Saves 9 min per renewal",
    hoursSavedWeekly: 7, dollarsSavedMonthly: 3200, rating: 4.8, ratingCount: 41, setupMinutes: 15,
    requirements: ["AMS", "Gmail"],
    steps: ["Pulls renewals 45 days out", "Drafts personalized email per client", "Suggests cross-sell gaps", "Monday delivery"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "quote-followup", roleSlug: "insurance-agent",
    name: "Auto follow-up 6 times on every unconverted quote",
    tagline: "Most quotes die from silence — not anymore.",
    description: "Drips 6 personalized follow-ups over 30 days to every unconverted quote.",
    category: "Sales",
    timePerAction: "Saves 4 min per touch",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 2800, rating: 4.7, ratingCount: 56, setupMinutes: 10,
    requirements: ["AMS", "Gmail"],
    steps: ["Detects new quote", "Schedules 6-touch sequence", "Personalizes each touch", "Stops on response"],
    source: "Zapier", sourceUrl: "https://zapier.com", priceModel: "freemium",
  }),
  wf({
    slug: "claims-status-updates", roleSlug: "insurance-agent",
    name: "Email clients plain-English claim status updates",
    tagline: "Translate carrier-speak into something humans understand.",
    description: "Watches carrier portals for claim updates and emails the insured an explanation in plain English.",
    category: "Operations",
    timePerAction: "Saves 8 min per claim update",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 1400, rating: 4.6, ratingCount: 27, setupMinutes: 25,
    requirements: ["Carrier portal", "Gmail"],
    steps: ["Polls carrier portals", "Translates insurance-speak", "Drafts plain-English update", "Lands in Gmail Drafts"],
    source: "n8n", sourceUrl: "https://n8n.io/workflows", priceModel: "free",
  }),
  wf({
    slug: "x-date-tracker", roleSlug: "insurance-agent",
    name: "Track prospect X-dates and outreach 30 days before",
    tagline: "Never miss a renewal you've been waiting on.",
    description: "Maintains X-date list and triggers outreach 30 days before competitor's renewal.",
    category: "Sales",
    timePerAction: "Saves 5 min per X-date touch",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 2100, rating: 4.5, ratingCount: 19, setupMinutes: 15,
    requirements: ["Google Sheets", "Gmail"],
    steps: ["Maintains X-date sheet", "Friday digest of next month", "Drafts outreach 30 days out", "Logs every touch"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ INSURANCE BROKER ============
  wf({
    slug: "market-shop-comparison", roleSlug: "insurance-broker",
    name: "Quote across 8+ carriers in one click",
    tagline: "Auto-fan a single submission to your full market.",
    description: "Submits one application across your full carrier market, normalizes responses into a side-by-side comparison.",
    category: "Sales",
    timePerAction: "Saves 35 min per submission",
    hoursSavedWeekly: 8, dollarsSavedMonthly: 4200, rating: 4.8, ratingCount: 24, setupMinutes: 30,
    requirements: ["Carrier APIs", "Gmail"],
    steps: ["Submits to all carriers", "Normalizes coverage + premium", "Generates comparison PDF", "Emails to producer"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "carrier-appetite-matcher", roleSlug: "insurance-broker",
    name: "Match new submissions to the right carrier instantly",
    tagline: "Stop submitting to carriers that will decline.",
    description: "Analyzes incoming submissions against carrier appetite guides and recommends top 3 carriers to approach.",
    category: "Sales",
    timePerAction: "Saves 12 min per submission",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 1800, rating: 4.7, ratingCount: 18, setupMinutes: 20,
    requirements: ["Submission intake form", "Carrier appetite docs"],
    steps: ["Parses submission details", "Cross-references appetite guides", "Ranks top 3 fits", "Drafts cover letters"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "commission-reconciliation", roleSlug: "insurance-broker",
    name: "Reconcile carrier commission statements automatically",
    tagline: "Catch underpayments without the spreadsheet hell.",
    description: "Parses every carrier commission statement, cross-references your book, flags discrepancies.",
    category: "Admin",
    timePerAction: "Saves 18 min per statement",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 2400, rating: 4.6, ratingCount: 12, setupMinutes: 25,
    requirements: ["AMS", "Carrier statements (PDF)"],
    steps: ["OCR each statement", "Cross-references AMS data", "Flags discrepancies", "Monthly summary report"],
    source: "Make", sourceUrl: "https://make.com", priceModel: "freemium",
  }),
  wf({
    slug: "endorsement-automation", roleSlug: "insurance-broker",
    name: "Auto-handle endorsement requests end-to-end",
    tagline: "Tenant adds a roommate? Done in 2 minutes.",
    description: "Watches for endorsement requests in email, drafts the change to the carrier, updates AMS, emails the insured.",
    category: "Operations",
    timePerAction: "Saves 11 min per endorsement",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 1600, rating: 4.7, ratingCount: 21, setupMinutes: 20,
    requirements: ["AMS", "Gmail"],
    steps: ["Detects endorsement request emails", "Drafts carrier change form", "Updates AMS", "Confirms with insured"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ MORTGAGE LOAN OFFICER ============
  wf({
    slug: "rate-watch-alerts", roleSlug: "mortgage-loan-officer",
    name: "Email past borrowers when rates drop enough to refi",
    tagline: "Trigger refi outreach the moment math works.",
    description: "Watches the 30-year fixed. When it drops 0.5%+ from a past borrower's locked rate, drafts a personalized refi outreach.",
    category: "Past clients",
    timePerAction: "Saves 14 min per refi outreach",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 5200, rating: 4.9, ratingCount: 34, setupMinutes: 20,
    requirements: ["LOS export", "Gmail", "FRED API"],
    steps: ["Polls Freddie Mac rates daily", "Cross-references locked rates", "Identifies refi candidates", "Drafts savings-personalized email"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "pre-approval-followup", roleSlug: "mortgage-loan-officer",
    name: "Weekly check-ins with pre-approved buyers",
    tagline: "Stay top of mind until they find a home.",
    description: "Sends a personalized weekly check-in to every pre-approved buyer who hasn't applied yet.",
    category: "Sales",
    timePerAction: "Saves 6 min per check-in",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 1800, rating: 4.6, ratingCount: 22, setupMinutes: 10,
    requirements: ["Gmail", "Google Sheets"],
    steps: ["Tracks pre-approvals without apps", "Weekly personalized check-in", "Includes rate forecast", "Auto-stops on application"],
    source: "Make", sourceUrl: "https://make.com/templates", priceModel: "freemium",
  }),
  wf({
    slug: "realtor-referral-tracker", roleSlug: "mortgage-loan-officer",
    name: "Rank and thank Realtor partners by referral volume",
    tagline: "Reward your best referrers automatically.",
    description: "Tracks every closed deal by referring agent. Monthly digest of top referrers + drafted thank-you / co-marketing offers.",
    category: "Operations",
    timePerAction: "Saves 9 min per partner touch",
    hoursSavedWeekly: 2, dollarsSavedMonthly: 900, rating: 4.5, ratingCount: 14, setupMinutes: 15,
    requirements: ["LOS", "Gmail"],
    steps: ["Imports closings", "Groups by agent", "Ranks by GCI", "Drafts monthly thank-you"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "doc-collection-bot", roleSlug: "mortgage-loan-officer",
    name: "Chase missing borrower docs without being annoying",
    tagline: "Polite but persistent doc reminders.",
    description: "Sends polite reminder emails + SMS until every required document is uploaded.",
    category: "Operations",
    timePerAction: "Saves 7 min per borrower",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 1200, rating: 4.7, ratingCount: 28, setupMinutes: 12,
    requirements: ["LOS", "Twilio"],
    steps: ["Watches missing docs in LOS", "Sends polite reminder day 1, 3, 5", "Escalates after 7 days", "Logs each touch"],
    source: "n8n", sourceUrl: "https://n8n.io/workflows", priceModel: "free",
  }),

  // ============ SOLO ATTORNEY ============
  wf({
    slug: "intake-screener", roleSlug: "solo-attorney",
    name: "Filter intake forms and book only viable cases",
    tagline: "Stop wasting consults on cases you can't take.",
    description: "Intake form responses get evaluated against your case criteria. Strong cases get a consult. Wrong fit gets a polite referral out.",
    category: "Sales",
    timePerAction: "Saves 22 min per intake",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 3800, rating: 4.7, ratingCount: 38, setupMinutes: 20,
    requirements: ["Typeform", "Gmail", "Calendly"],
    steps: ["Form triggers analysis", "Evaluates against your criteria", "Strong fits: calendar link", "Wrong fits: referral drafted"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "court-date-reminders", roleSlug: "solo-attorney",
    name: "Multi-channel reminders for every filing & court date",
    tagline: "Never miss a deadline again.",
    description: "Watches case management for upcoming deadlines. Multi-channel reminders 7/3/1 days out.",
    category: "Compliance",
    timePerAction: "Saves 4 min per deadline tracked",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 2200, rating: 4.9, ratingCount: 24, setupMinutes: 15,
    requirements: ["Clio / MyCase"],
    steps: ["Syncs case deadlines", "7-day reminder", "3-day reminder", "1-day reminder"],
    source: "Zapier", sourceUrl: "https://zapier.com/apps/clio", priceModel: "freemium",
  }),
  wf({
    slug: "contract-review", roleSlug: "solo-attorney",
    name: "Spot 10 red flags in any contract in 60 seconds",
    tagline: "First-pass contract review at lightspeed.",
    description: "Drop a PDF. Get a 1-page summary, key risks, missing clauses, and suggested redlines.",
    category: "Admin",
    timePerAction: "Saves 38 min per contract",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 4400, rating: 4.6, ratingCount: 167, setupMinutes: 2,
    requirements: ["Claude"],
    steps: ["Drop PDF", "Generates summary", "Flags top 10 red flags", "Suggests redline language"],
    source: "Claude Skills", sourceUrl: "https://anthropic.com/claude/skills", priceModel: "paid",
  }),
  wf({
    slug: "billing-auto-drafter", roleSlug: "solo-attorney",
    name: "Draft client invoices from time entries automatically",
    tagline: "Monthly billing in 15 minutes instead of 4 hours.",
    description: "Reads time entries, groups by matter, drafts professional invoices ready to send.",
    category: "Admin",
    timePerAction: "Saves 9 min per invoice",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 2400, rating: 4.6, ratingCount: 31, setupMinutes: 15,
    requirements: ["Clio / TimeSolv"],
    steps: ["Reads time entries", "Groups by matter", "Drafts formatted invoice", "Sends for your approval"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ PERSONAL INJURY ATTORNEY ============
  wf({
    slug: "case-value-estimator", roleSlug: "personal-injury-attorney",
    name: "Estimate case value from intake details in seconds",
    tagline: "Know what a case is worth before the first call.",
    description: "Takes intake form details and produces a probability-weighted settlement range using comparable case data.",
    category: "Sales",
    timePerAction: "Saves 18 min per case eval",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 5200, rating: 4.7, ratingCount: 19, setupMinutes: 20,
    requirements: ["Intake form", "Comp database"],
    steps: ["Parses intake details", "Looks up comparable settlements", "Generates probability range", "Routes high-value to senior atty"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "medical-records-requester", roleSlug: "personal-injury-attorney",
    name: "Auto-request medical records from every provider",
    tagline: "Records requests sent same day as sign-up.",
    description: "Generates and sends HIPAA-compliant records request letters to every provider in client's treatment history.",
    category: "Admin",
    timePerAction: "Saves 14 min per provider",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 2400, rating: 4.8, ratingCount: 28, setupMinutes: 25,
    requirements: ["Filevine / CASEpeer", "Gmail"],
    steps: ["Reads treatment provider list", "Generates HIPAA-compliant request", "Sends + tracks delivery", "Auto-follow-up if delayed"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "demand-letter-builder", roleSlug: "personal-injury-attorney",
    name: "Draft demand letters from medical records",
    tagline: "First-draft demand in 10 minutes.",
    description: "Reads medical records and bills. Drafts a structured demand letter with damages breakdown.",
    category: "Sales",
    timePerAction: "Saves 90 min per demand",
    hoursSavedWeekly: 8, dollarsSavedMonthly: 6500, rating: 4.5, ratingCount: 22, setupMinutes: 20,
    requirements: ["Medical records (PDF)", "Claude"],
    steps: ["OCR medical records + bills", "Summarizes injuries + treatment", "Calculates damages", "Drafts structured demand"],
    source: "Claude Skills", sourceUrl: "https://anthropic.com/claude/skills", priceModel: "paid",
  }),
  wf({
    slug: "client-status-updates", roleSlug: "personal-injury-attorney",
    name: "Weekly case status updates to every active client",
    tagline: "Reduce \"any update?\" calls by 80%.",
    description: "Auto-drafts weekly case status updates with what happened, what's next, and timing expectations.",
    category: "Past clients",
    timePerAction: "Saves 5 min per client",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 1800, rating: 4.7, ratingCount: 16, setupMinutes: 15,
    requirements: ["Case management", "Gmail"],
    steps: ["Reads case activity", "Drafts plain-English update", "Includes next step + timing", "Friday delivery"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ DENTAL OFFICE MANAGER ============
  wf({
    slug: "patient-recall", roleSlug: "dental-office-manager",
    name: "Auto-remind patients due for cleanings via SMS & email",
    tagline: "Recall every patient automatically.",
    description: "Pulls patients due for 6-month cleanings and sends a personalized recall via email + SMS with booking link.",
    category: "Recall",
    timePerAction: "Saves 3 min per patient recall",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 4800, rating: 4.8, ratingCount: 41, setupMinutes: 25,
    requirements: ["Dentrix / Open Dental", "Twilio"],
    steps: ["Queries PMS for due recalls", "Personalized SMS + email", "One-click booking link", "Follow-up if no response"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "no-show-recovery", roleSlug: "dental-office-manager",
    name: "Same-day reschedule outreach when a patient no-shows",
    tagline: "Recover 40% of no-shows.",
    description: "When a patient no-shows, an empathetic reschedule message goes out within 2 hours.",
    category: "Recall",
    timePerAction: "Saves 6 min per no-show",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 2400, rating: 4.6, ratingCount: 28, setupMinutes: 15,
    requirements: ["PMS", "Twilio"],
    steps: ["Detects no-show", "2-hour delay", "Empathetic SMS with 3 slots", "Books directly if confirmed"],
    source: "n8n", sourceUrl: "https://n8n.io/workflows", priceModel: "free",
  }),
  wf({
    slug: "insurance-verification", roleSlug: "dental-office-manager",
    name: "Verify insurance 24h before every appointment",
    tagline: "Stop the morning-of surprises.",
    description: "Pulls tomorrow's schedule and auto-verifies each patient's insurance benefits.",
    category: "Admin",
    timePerAction: "Saves 8 min per verification",
    hoursSavedWeekly: 8, dollarsSavedMonthly: 3600, rating: 4.7, ratingCount: 52, setupMinutes: 30,
    requirements: ["PMS", "Verification API"],
    steps: ["Pulls tomorrow's appts", "Queries benefits per patient", "Updates patient record", "Morning digest"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "treatment-plan-followup", roleSlug: "dental-office-manager",
    name: "Convert unscheduled treatment plans into bookings",
    tagline: "Don't let $50K of unscheduled treatment sit there.",
    description: "Drips reminders to patients with accepted-but-unscheduled treatment plans.",
    category: "Past clients",
    timePerAction: "Saves 4 min per touch",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 5800, rating: 4.7, ratingCount: 18, setupMinutes: 20,
    requirements: ["PMS", "Gmail", "Twilio"],
    steps: ["Pulls unscheduled tx plans", "Drips reminders week 2, 4, 8", "Includes treatment benefit reminder", "Books on response"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ DENTIST (Owner) ============
  wf({
    slug: "clinical-note-helper", roleSlug: "dentist",
    name: "Voice-to-clinical-note in 30 seconds per patient",
    tagline: "Dictate. Get back a structured chart note.",
    description: "Dictate after each patient. Get back SOAP-formatted clinical notes ready to paste into the chart.",
    category: "Admin",
    timePerAction: "Saves 4 min per patient note",
    hoursSavedWeekly: 8, dollarsSavedMonthly: 3200, rating: 4.8, ratingCount: 64, setupMinutes: 10,
    requirements: ["Phone or recorder", "Claude"],
    steps: ["Record voice memo per patient", "Transcribed + structured", "SOAP-formatted output", "Paste into chart"],
    featured: true, source: "Claude Skills", sourceUrl: "https://anthropic.com/claude/skills", priceModel: "paid",
  }),
  wf({
    slug: "patient-review-requests", roleSlug: "dentist",
    name: "Request Google reviews from happy patients automatically",
    tagline: "Turn smiles into 5-star reviews.",
    description: "Sends review request to patients 24 hours after positive treatment outcomes.",
    category: "Marketing",
    timePerAction: "Saves 2 min per request",
    hoursSavedWeekly: 2, dollarsSavedMonthly: 1800, rating: 4.6, ratingCount: 41, setupMinutes: 12,
    requirements: ["PMS", "Twilio"],
    steps: ["Detects positive visit", "24-hour delay", "Sends SMS with review link", "Tracks response"],
    source: "Zapier", sourceUrl: "https://zapier.com", priceModel: "freemium",
  }),
  wf({
    slug: "production-dashboard", roleSlug: "dentist",
    name: "Daily production dashboard for your practice",
    tagline: "Know your numbers before your morning coffee.",
    description: "Sends you a morning email with yesterday's production, today's schedule, and KPIs.",
    category: "Operations",
    timePerAction: "Saves 8 min per day",
    hoursSavedWeekly: 1, dollarsSavedMonthly: 600, rating: 4.5, ratingCount: 22, setupMinutes: 20,
    requirements: ["PMS"],
    steps: ["Pulls overnight production", "Calculates KPIs", "Generates AM dashboard", "Email at 6am"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "case-acceptance-helper", roleSlug: "dentist",
    name: "Personalized case-acceptance follow-ups after consults",
    tagline: "Convert more case presentations into yeses.",
    description: "After a treatment consultation, sends a personalized follow-up with benefits + financing options.",
    category: "Sales",
    timePerAction: "Saves 7 min per consult follow-up",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 4200, rating: 4.7, ratingCount: 19, setupMinutes: 15,
    requirements: ["PMS", "Gmail"],
    steps: ["Detects completed consult", "Drafts personalized follow-up", "Includes benefits + financing", "Schedules follow-up if no response"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ PRIVATE PRACTICE PHYSICIAN ============
  wf({
    slug: "patient-intake-summarizer", roleSlug: "private-practice-physician",
    name: "Summarize new patient intake forms into a 1-pager",
    tagline: "Walk into every visit prepped.",
    description: "Reads new patient intake forms and produces a structured 1-page summary for the chart.",
    category: "Admin",
    timePerAction: "Saves 8 min per new patient",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 1800, rating: 4.7, ratingCount: 28, setupMinutes: 15,
    requirements: ["EHR", "Intake form"],
    steps: ["Reads intake form", "Extracts history + concerns", "Generates 1-page summary", "Attaches to chart"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "prior-auth-helper", roleSlug: "private-practice-physician",
    name: "Auto-draft prior authorization letters",
    tagline: "Prior auths done in 5 minutes, not 45.",
    description: "Generates payer-specific prior authorization letters from patient chart and proposed treatment.",
    category: "Admin",
    timePerAction: "Saves 35 min per prior auth",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 2400, rating: 4.8, ratingCount: 41, setupMinutes: 25,
    requirements: ["EHR", "Payer guidelines"],
    steps: ["Reads chart + proposed tx", "Generates payer-specific letter", "Includes medical necessity", "Submits via portal"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "appointment-reminder", roleSlug: "private-practice-physician",
    name: "Multi-touch appointment reminders to reduce no-shows",
    tagline: "Drop no-show rate from 18% to 4%.",
    description: "Sends reminders 7 days, 24 hours, and 2 hours before each appointment.",
    category: "Recall",
    timePerAction: "Saves 4 min per appointment",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 2200, rating: 4.6, ratingCount: 52, setupMinutes: 12,
    requirements: ["EHR", "Twilio"],
    steps: ["Pulls upcoming appts", "7-day SMS reminder", "24-hour reminder", "2-hour reminder with reschedule link"],
    source: "Zapier", sourceUrl: "https://zapier.com", priceModel: "freemium",
  }),
  wf({
    slug: "lab-result-notifier", roleSlug: "private-practice-physician",
    name: "Notify patients of normal lab results automatically",
    tagline: "Stop the lab-result phone tag.",
    description: "When labs come back normal, auto-drafts a patient-friendly explanation email for your approval.",
    category: "Operations",
    timePerAction: "Saves 4 min per normal result",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 1500, rating: 4.7, ratingCount: 34, setupMinutes: 18,
    requirements: ["EHR", "Lab API"],
    steps: ["Watches lab results", "Auto-classifies normal vs abnormal", "Drafts plain-English email", "You approve, sends"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ HVAC CONTRACTOR ============
  wf({
    slug: "service-lead-responder", roleSlug: "hvac-contractor",
    name: "Reply to service requests in under 5 minutes 24/7",
    tagline: "Be the first contractor to respond, win the job.",
    description: "Watches Google forms, Angi, Thumbtack, and Yelp. Auto-replies with availability and triages urgency.",
    category: "Lead gen",
    timePerAction: "Saves 4 min per inquiry",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 3200, rating: 4.8, ratingCount: 38, setupMinutes: 15,
    requirements: ["Gmail", "Angi / Thumbtack", "Twilio"],
    steps: ["Watches all lead sources", "Classifies urgency (emergency / routine)", "Auto-reply with availability", "Books or routes to dispatch"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "maintenance-membership-renewals", roleSlug: "hvac-contractor",
    name: "Auto-renew maintenance memberships before they lapse",
    tagline: "Membership churn down 60%.",
    description: "Watches membership expirations. Sends renewal reminders + auto-charges card on file.",
    category: "Past clients",
    timePerAction: "Saves 5 min per renewal",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 2800, rating: 4.7, ratingCount: 24, setupMinutes: 18,
    requirements: ["ServiceTitan / Housecall Pro", "Stripe"],
    steps: ["Pulls expiring memberships", "30-day reminder", "Auto-charges card", "Confirms renewal"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "post-job-review-request", roleSlug: "hvac-contractor",
    name: "Request Google reviews 24h after every completed job",
    tagline: "Get more 5-star reviews on autopilot.",
    description: "Sends a review request via SMS 24 hours after a tech marks a job complete.",
    category: "Marketing",
    timePerAction: "Saves 2 min per request",
    hoursSavedWeekly: 2, dollarsSavedMonthly: 1800, rating: 4.6, ratingCount: 56, setupMinutes: 10,
    requirements: ["FSM software", "Twilio"],
    steps: ["Watches completed jobs", "24-hour delay", "Personalized SMS with link", "Tracks review submission"],
    source: "Zapier", sourceUrl: "https://zapier.com", priceModel: "freemium",
  }),
  wf({
    slug: "seasonal-tune-up-campaign", roleSlug: "hvac-contractor",
    name: "Outreach to past customers before each season",
    tagline: "Book a quarter of your spring & fall slots from past customers.",
    description: "Sends seasonal tune-up reminders to past customers 30 days before peak season.",
    category: "Past clients",
    timePerAction: "Saves 3 min per outreach",
    hoursSavedWeekly: 2, dollarsSavedMonthly: 4200, rating: 4.7, ratingCount: 22, setupMinutes: 15,
    requirements: ["Customer DB", "Gmail", "Twilio"],
    steps: ["Pulls past customer list", "Spring + fall pre-season trigger", "Personalized SMS + email", "One-click booking"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ ROOFING CONTRACTOR ============
  wf({
    slug: "storm-area-prospector", roleSlug: "roofing-contractor",
    name: "Identify homes hit by recent storms in your service area",
    tagline: "Get to the door before the competition.",
    description: "Monitors NOAA storm data. Pulls property records for affected homes. Drafts personalized outreach.",
    category: "Lead gen",
    timePerAction: "Saves 28 min per qualified address",
    hoursSavedWeekly: 8, dollarsSavedMonthly: 8400, rating: 4.8, ratingCount: 19, setupMinutes: 25,
    requirements: ["NOAA API", "Property records", "Gmail"],
    steps: ["Watches storm reports", "Cross-references property records", "Generates affected address list", "Drafts personalized door cards"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "estimate-followup", roleSlug: "roofing-contractor",
    name: "Auto follow-up on outstanding estimates for 30 days",
    tagline: "Close more estimates with consistent follow-up.",
    description: "Drips 5 personalized touches to homeowners who got an estimate but haven't signed.",
    category: "Sales",
    timePerAction: "Saves 5 min per touch",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 5400, rating: 4.7, ratingCount: 28, setupMinutes: 15,
    requirements: ["CRM", "Gmail", "Twilio"],
    steps: ["Detects unsigned estimate", "Schedules 5-touch sequence", "Personalized to job specifics", "Stops on response"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "insurance-claim-helper", roleSlug: "roofing-contractor",
    name: "Help homeowners file insurance claims for hail damage",
    tagline: "Make filing easier — close more deals.",
    description: "Walks the homeowner through claim filing with a step-by-step guide tailored to their carrier.",
    category: "Sales",
    timePerAction: "Saves 25 min per homeowner",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 4800, rating: 4.6, ratingCount: 14, setupMinutes: 20,
    requirements: ["Carrier guides", "Gmail"],
    steps: ["Identifies carrier", "Generates step-by-step guide", "Drafts emails to carrier", "Tracks claim status"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "warranty-renewal-tracker", roleSlug: "roofing-contractor",
    name: "Reach out to customers as warranties approach end",
    tagline: "Re-engage customers in year 9 of a 10-year warranty.",
    description: "Watches warranty expirations and sends reminders + inspection offers before they lapse.",
    category: "Past clients",
    timePerAction: "Saves 6 min per outreach",
    hoursSavedWeekly: 2, dollarsSavedMonthly: 2600, rating: 4.5, ratingCount: 11, setupMinutes: 15,
    requirements: ["Customer DB", "Gmail"],
    steps: ["Pulls warranties expiring in 12 months", "Drafts inspection offer", "Includes photo timeline", "Monthly outreach"],
    source: "n8n", sourceUrl: "https://n8n.io/workflows", priceModel: "free",
  }),

  // ============ SOLAR INSTALLER ============
  wf({
    slug: "savings-calculator-leads", roleSlug: "solar-installer",
    name: "Auto-calculate solar savings for inbound leads",
    tagline: "Personalized savings estimate within 5 minutes.",
    description: "Pulls home address, estimates roof + sun exposure, calculates savings projection.",
    category: "Lead gen",
    timePerAction: "Saves 22 min per lead",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 6800, rating: 4.8, ratingCount: 31, setupMinutes: 25,
    requirements: ["Address", "Google Solar API", "Gmail"],
    steps: ["Looks up address", "Estimates roof + sun exposure", "Calculates 20-year savings", "Sends personalized PDF"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "rebate-tracker", roleSlug: "solar-installer",
    name: "Track federal + state + utility rebates for every customer",
    tagline: "Capture every rebate dollar your customers deserve.",
    description: "Auto-files paperwork for federal ITC, state credits, and utility rebates per customer.",
    category: "Admin",
    timePerAction: "Saves 32 min per install",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 2200, rating: 4.7, ratingCount: 18, setupMinutes: 30,
    requirements: ["CRM", "State/utility portals"],
    steps: ["Identifies eligible rebates by address", "Generates paperwork", "Submits to portals", "Tracks status"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "post-install-monitoring", roleSlug: "solar-installer",
    name: "Monitor every install for underperformance",
    tagline: "Catch system issues before customers notice.",
    description: "Watches production data from monitoring portals. Alerts you when systems underperform expectations.",
    category: "Operations",
    timePerAction: "Saves 12 min per issue",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 1800, rating: 4.7, ratingCount: 22, setupMinutes: 20,
    requirements: ["SolarEdge / Enphase API"],
    steps: ["Polls monitoring data daily", "Compares to expected production", "Alerts on 15%+ underperformance", "Drafts customer outreach"],
    source: "n8n", sourceUrl: "https://n8n.io/workflows", priceModel: "free",
  }),
  wf({
    slug: "referral-program-engine", roleSlug: "solar-installer",
    name: "Automated referral program for happy solar customers",
    tagline: "Turn one install into three.",
    description: "Triggers referral asks after positive monitoring data + sends thank-you payments when referrals close.",
    category: "Past clients",
    timePerAction: "Saves 6 min per referral touch",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 4200, rating: 4.6, ratingCount: 14, setupMinutes: 18,
    requirements: ["CRM", "Stripe", "Twilio"],
    steps: ["Watches positive monitoring", "Triggers referral ask SMS", "Tracks referred leads", "Auto-pays on close"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ MED SPA OWNER ============
  wf({
    slug: "follow-up-treatment-protocol", roleSlug: "med-spa-owner",
    name: "Auto check-in 48h and 2 weeks after every treatment",
    tagline: "Loyalty + early complication detection.",
    description: "Automatic check-ins after injectables, lasers, or facials. Builds loyalty and surfaces complications early.",
    category: "Recall",
    timePerAction: "Saves 4 min per treatment",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 3200, rating: 4.8, ratingCount: 64, setupMinutes: 20,
    requirements: ["PMS (Boulevard)", "Twilio"],
    steps: ["Detects completed treatment", "48-hour check-in SMS", "2-week follow-up with rebook link", "Flags negative responses"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "rebooking-cadence", roleSlug: "med-spa-owner",
    name: "Personalized rebooking reminders by treatment type",
    tagline: "Botox 3 months out. Laser 6 weeks. Done.",
    description: "Sends treatment-specific rebooking reminders at the right cadence for each service.",
    category: "Past clients",
    timePerAction: "Saves 3 min per reminder",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 4800, rating: 4.7, ratingCount: 41, setupMinutes: 15,
    requirements: ["PMS", "Twilio"],
    steps: ["Maps treatment to cadence", "Reminds at optimal interval", "Personalized to client history", "Books on response"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "treatment-package-upsell", roleSlug: "med-spa-owner",
    name: "Suggest treatment packages based on client history",
    tagline: "Increase average ticket by suggesting the right add-on.",
    description: "Analyzes client treatment history and suggests personalized packages at the right moment.",
    category: "Sales",
    timePerAction: "Saves 5 min per recommendation",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 5400, rating: 4.6, ratingCount: 22, setupMinutes: 18,
    requirements: ["PMS", "Gmail"],
    steps: ["Analyzes treatment history", "Identifies package fit", "Drafts personalized recommendation", "Sends 7 days before next visit"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "lapsed-client-winback", roleSlug: "med-spa-owner",
    name: "Win back clients who haven't booked in 90+ days",
    tagline: "Re-engage your sleeping book.",
    description: "Identifies lapsed clients and sends personalized winback offers with a discount.",
    category: "Past clients",
    timePerAction: "Saves 4 min per winback",
    hoursSavedWeekly: 2, dollarsSavedMonthly: 3600, rating: 4.5, ratingCount: 18, setupMinutes: 12,
    requirements: ["PMS", "Twilio"],
    steps: ["Identifies 90-day lapsed", "Drafts personalized winback", "Includes targeted discount", "Books on response"],
    source: "Zapier", sourceUrl: "https://zapier.com", priceModel: "freemium",
  }),

  // ============ FINANCIAL ADVISOR ============
  wf({
    slug: "rmd-reminders", roleSlug: "financial-advisor",
    name: "Track and remind every client about RMDs",
    tagline: "Never let a client miss their RMD again.",
    description: "Watches every client's RMD status and sends reminders before year-end deadlines.",
    category: "Compliance",
    timePerAction: "Saves 8 min per RMD review",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 3200, rating: 4.8, ratingCount: 24, setupMinutes: 20,
    requirements: ["CRM", "Custodian data", "Gmail"],
    steps: ["Pulls RMD-eligible clients", "Tracks YTD distributions", "Q3 reminder, Q4 urgent", "Drafts personalized email"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "quarterly-review-prep", roleSlug: "financial-advisor",
    name: "Generate quarterly client review materials automatically",
    tagline: "Walk into every QBR with a polished deck.",
    description: "Pulls portfolio performance, generates branded review materials, drafts agenda.",
    category: "Operations",
    timePerAction: "Saves 35 min per QBR",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 4800, rating: 4.7, ratingCount: 31, setupMinutes: 25,
    requirements: ["Portfolio management", "Gmail"],
    steps: ["Pulls portfolio performance", "Generates branded materials", "Drafts agenda + talking points", "Email 3 days before meeting"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "client-birthday-touches", roleSlug: "financial-advisor",
    name: "Personalized birthday + anniversary touches",
    tagline: "Stay top of mind without remembering anything.",
    description: "Personalized birthday + relationship anniversary emails to every client.",
    category: "Past clients",
    timePerAction: "Saves 3 min per touch",
    hoursSavedWeekly: 2, dollarsSavedMonthly: 1200, rating: 4.6, ratingCount: 28, setupMinutes: 10,
    requirements: ["CRM", "Gmail"],
    steps: ["Reads client DOB + anniv", "Drafts personalized note", "Sends day-of", "Logs touch in CRM"],
    source: "Zapier", sourceUrl: "https://zapier.com", priceModel: "freemium",
  }),
  wf({
    slug: "market-volatility-outreach", roleSlug: "financial-advisor",
    name: "Calming outreach to clients during market drops",
    tagline: "Reassure clients before they call you panicked.",
    description: "When markets drop 3%+, auto-drafts a calming outreach to your top 50 clients.",
    category: "Past clients",
    timePerAction: "Saves 5 min per outreach",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 1800, rating: 4.7, ratingCount: 19, setupMinutes: 15,
    requirements: ["Market API", "CRM", "Gmail"],
    steps: ["Watches S&P daily change", "Triggers on 3%+ drop", "Personalizes to each client portfolio", "Drafts calming message"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ AGENCY OWNER ============
  wf({
    slug: "weekly-client-reports", roleSlug: "agency-owner",
    name: "Generate personalized client reports every Monday",
    tagline: "Polished reports without manual data pulling.",
    description: "Pulls data from GA4, Meta Ads, Google Ads, Search Console. Drafts personalized weekly report per client.",
    category: "Operations",
    timePerAction: "Saves 22 min per client report",
    hoursSavedWeekly: 10, dollarsSavedMonthly: 4800, rating: 4.7, ratingCount: 92, setupMinutes: 30,
    requirements: ["GA4", "Meta Ads", "Google Ads"],
    steps: ["Pulls last week's data", "Generates KPIs + YoY comparisons", "Drafts personalized narrative", "Monday 7am delivery"],
    featured: true, source: "Make", sourceUrl: "https://make.com/templates", priceModel: "freemium",
  }),
  wf({
    slug: "proposal-generator", roleSlug: "agency-owner",
    name: "Turn discovery notes into a branded proposal",
    tagline: "Proposal in 5 minutes, not 5 hours.",
    description: "Paste discovery call notes. Get a fully-formatted proposal with scope, timeline, pricing.",
    category: "Sales",
    timePerAction: "Saves 90 min per proposal",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 3200, rating: 4.6, ratingCount: 47, setupMinutes: 10,
    requirements: ["Google Docs", "Claude"],
    steps: ["Paste discovery notes", "Generates scope + deliverables", "Pulls pricing from template", "Outputs branded Doc"],
    source: "GPT Store", sourceUrl: "https://chat.openai.com/gpts", priceModel: "freemium",
  }),
  wf({
    slug: "client-checkin-cadence", roleSlug: "agency-owner",
    name: "Auto-schedule client check-ins to prevent churn",
    tagline: "Never lose a client to silence.",
    description: "Watches client touch points. Triggers check-in reminders when accounts go quiet.",
    category: "Past clients",
    timePerAction: "Saves 5 min per touch",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 6400, rating: 4.7, ratingCount: 22, setupMinutes: 15,
    requirements: ["CRM", "Slack"],
    steps: ["Tracks last client touch", "Alerts if no touch in 14 days", "Drafts check-in", "Books call if needed"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "scope-creep-detector", roleSlug: "agency-owner",
    name: "Detect scope creep in client requests automatically",
    tagline: "Stop eating extra work.",
    description: "Reads client emails + Slack messages. Flags requests that exceed agreed scope and drafts a change-order response.",
    category: "Operations",
    timePerAction: "Saves 12 min per scope flag",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 5800, rating: 4.7, ratingCount: 18, setupMinutes: 18,
    requirements: ["SOW docs", "Gmail", "Slack"],
    steps: ["Reads incoming requests", "Cross-references SOW", "Flags out-of-scope items", "Drafts change-order response"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ COACH / CONSULTANT ============
  wf({
    slug: "client-session-prep", roleSlug: "coach-consultant",
    name: "Auto-brief before every coaching session",
    tagline: "10-minute prep done before you sit down.",
    description: "Pulls last session notes + recent client emails + active goals. Generates 1-page brief before each call.",
    category: "Operations",
    timePerAction: "Saves 9 min per session prep",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 1600, rating: 4.8, ratingCount: 73, setupMinutes: 15,
    requirements: ["Gmail", "Notion"],
    steps: ["Reads last session notes", "Scans recent emails", "Pulls active goals", "1-page brief 1hr pre-call"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "content-repurposing", roleSlug: "coach-consultant",
    name: "Turn one podcast into 12 pieces of content",
    tagline: "One episode → blog, carousel, thread, captions.",
    description: "Record once. Get a blog post, LinkedIn carousel, Twitter thread, Instagram captions, YouTube chapters.",
    category: "Marketing",
    timePerAction: "Saves 4 hrs per episode",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 2400, rating: 4.7, ratingCount: 248, setupMinutes: 5,
    requirements: ["Descript / Otter", "Claude"],
    steps: ["Drop transcript", "Extract top 5 insights", "Generate blog + carousel", "Generate thread + captions"],
    source: "GPT Store", sourceUrl: "https://chat.openai.com/gpts", priceModel: "freemium",
  }),
  wf({
    slug: "client-progress-tracker", roleSlug: "coach-consultant",
    name: "Track every client's progress against their goals",
    tagline: "Show clients exactly how far they've come.",
    description: "Reads session notes weekly. Tracks progress per goal. Generates client-facing progress reports monthly.",
    category: "Operations",
    timePerAction: "Saves 18 min per client",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 3200, rating: 4.6, ratingCount: 22, setupMinutes: 20,
    requirements: ["Notion", "Gmail"],
    steps: ["Reads session notes weekly", "Updates goal progress", "Generates monthly report", "Sends to client"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "lead-nurture-sequence", roleSlug: "coach-consultant",
    name: "Nurture warm leads with personalized weekly touches",
    tagline: "Stay top of mind for 90 days without lifting a finger.",
    description: "Drips personalized educational content to warm leads who haven't booked yet.",
    category: "Lead gen",
    timePerAction: "Saves 4 min per nurture touch",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 4400, rating: 4.5, ratingCount: 38, setupMinutes: 15,
    requirements: ["CRM", "Gmail"],
    steps: ["Adds warm leads to sequence", "Weekly personalized email", "Includes relevant case study", "Stops on booking"],
    source: "Zapier", sourceUrl: "https://zapier.com", priceModel: "freemium",
  }),

  // ============ SAAS FOUNDER ============
  wf({
    slug: "weekly-investor-update", roleSlug: "saas-founder",
    name: "Draft weekly investor update from your live metrics",
    tagline: "Investor update in 10 minutes, not 90.",
    description: "Pulls MRR, churn, new logos, and pipeline from Stripe / HubSpot. Drafts a polished investor update every Friday.",
    category: "Operations",
    timePerAction: "Saves 75 min per update",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 1500, rating: 4.8, ratingCount: 89, setupMinutes: 30,
    requirements: ["Stripe", "HubSpot", "Gmail"],
    steps: ["Pulls MRR + churn", "Pulls pipeline data", "Generates narrative + KPI table", "Lands Friday AM"],
    featured: true, source: "Zapier", sourceUrl: "https://zapier.com/apps/integrations", priceModel: "freemium",
  }),
  wf({
    slug: "support-triage", roleSlug: "saas-founder",
    name: "Categorize, prioritize, and draft every support email",
    tagline: "30 seconds per ticket, not 8 minutes.",
    description: "Watches your support inbox. Classifies (bug / billing / how-to / churn risk). Drafts a response.",
    category: "Operations",
    timePerAction: "Saves 7.5 min per ticket",
    hoursSavedWeekly: 8, dollarsSavedMonthly: 4000, rating: 4.7, ratingCount: 156, setupMinutes: 20,
    requirements: ["Gmail / Intercom", "Claude"],
    steps: ["Polls inbox every 60s", "Classifies ticket type", "Flags churn-risk language", "Drafts tailored response"],
    featured: true, source: "Claude Skills", sourceUrl: "https://anthropic.com/claude/skills", priceModel: "paid",
  }),
  wf({
    slug: "linkedin-content-engine", roleSlug: "saas-founder",
    name: "Draft 5 LinkedIn posts every Sunday from your week",
    tagline: "Content from your wins, every week.",
    description: "Synthesizes your Slack, GitHub commits, and CRM wins into 5 LinkedIn post drafts every Sunday night.",
    category: "Marketing",
    timePerAction: "Saves 25 min per post",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 1200, rating: 4.6, ratingCount: 78, setupMinutes: 15,
    requirements: ["Slack", "GitHub", "Claude"],
    steps: ["Aggregates week's wins", "Identifies story moments", "Drafts 5 post variants", "Sunday 8pm delivery"],
    source: "n8n", sourceUrl: "https://n8n.io/workflows", priceModel: "free",
  }),
  wf({
    slug: "churn-risk-monitor", roleSlug: "saas-founder",
    name: "Get alerted the moment a customer shows churn signals",
    tagline: "Save accounts before they cancel.",
    description: "Watches usage drops, support sentiment, and login frequency. Alerts you to at-risk customers.",
    category: "Past clients",
    timePerAction: "Saves 28 min per at-risk save",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 6500, rating: 4.8, ratingCount: 62, setupMinutes: 30,
    requirements: ["Segment", "Stripe", "Slack"],
    steps: ["Tracks per-customer usage", "Detects 30%+ drops", "Scores churn risk", "Slack ping + outreach draft"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "inbound-lead-qualifier", roleSlug: "saas-founder",
    name: "Qualify, score, and route every demo request in 60s",
    tagline: "ICP-fit routing without manual review.",
    description: "Every demo request gets enriched, scored ICP fit, and either books on your calendar or gets a polite nurture.",
    category: "Lead gen",
    timePerAction: "Saves 12 min per inbound",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 3200, rating: 4.7, ratingCount: 134, setupMinutes: 20,
    requirements: ["Typeform", "Clay / Apollo", "Calendly"],
    steps: ["Form submission triggers", "Enriches lead data", "Scores ICP fit 1-10", "Routes by score"],
    source: "Zapier", sourceUrl: "https://zapier.com", priceModel: "paid",
  }),

  // ============ CUSTOMER SUCCESS LEAD ============
  wf({
    slug: "qbr-deck-builder", roleSlug: "customer-success-lead",
    name: "Auto-generate QBR decks from product usage data",
    tagline: "QBR deck in 5 minutes, not 4 hours.",
    description: "Pulls usage data, ticket history, and renewal milestones. Generates a branded QBR deck per account.",
    category: "Operations",
    timePerAction: "Saves 90 min per QBR",
    hoursSavedWeekly: 8, dollarsSavedMonthly: 5400, rating: 4.8, ratingCount: 34, setupMinutes: 30,
    requirements: ["Product analytics", "CRM", "Slides API"],
    steps: ["Pulls usage + ticket history", "Generates branded deck", "Includes adoption metrics", "Emails to CSM"],
    featured: true, source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "health-score-monitor", roleSlug: "customer-success-lead",
    name: "Update account health scores every Monday",
    tagline: "Know which accounts need love before standup.",
    description: "Computes health scores per account from usage + sentiment + tickets. Sends Monday digest.",
    category: "Operations",
    timePerAction: "Saves 18 min per account review",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 2400, rating: 4.7, ratingCount: 24, setupMinutes: 25,
    requirements: ["Segment / Amplitude", "Zendesk", "CRM"],
    steps: ["Aggregates usage data", "Pulls support ticket sentiment", "Computes health score 1-100", "Monday digest"],
    source: "n8n", sourceUrl: "https://n8n.io/workflows", priceModel: "free",
  }),
  wf({
    slug: "renewal-playbook", roleSlug: "customer-success-lead",
    name: "Trigger renewal playbook 120 days before contract end",
    tagline: "Start the renewal motion at the right moment.",
    description: "Watches contract end dates. Triggers tailored renewal playbook 120 days out.",
    category: "Past clients",
    timePerAction: "Saves 25 min per renewal motion",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 6800, rating: 4.7, ratingCount: 19, setupMinutes: 20,
    requirements: ["CRM", "Calendar"],
    steps: ["Watches contract end dates", "120-day trigger", "Schedules check-ins per playbook", "Drafts renewal outreach"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "onboarding-progress-tracker", roleSlug: "customer-success-lead",
    name: "Track onboarding milestones for every new customer",
    tagline: "Stop new customers from stalling.",
    description: "Watches new customer progress through onboarding milestones. Alerts CSM when an account stalls.",
    category: "Operations",
    timePerAction: "Saves 8 min per check-in",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 3400, rating: 4.6, ratingCount: 28, setupMinutes: 18,
    requirements: ["Product analytics", "Slack"],
    steps: ["Defines milestones per playbook", "Tracks progress per account", "Alerts when stalled 3+ days", "Drafts intervention"],
    source: "Monican", priceModel: "monican-setup",
  }),

  // ============ ECOMMERCE OWNER ============
  wf({
    slug: "abandoned-cart-recovery", roleSlug: "ecommerce-owner",
    name: "Personalized abandoned cart recovery sequences",
    tagline: "Recover 20-25% of abandoned carts.",
    description: "Sends a 3-touch recovery sequence: empathy + free shipping + last-chance discount.",
    category: "Sales",
    timePerAction: "Saves 1 min per cart",
    hoursSavedWeekly: 6, dollarsSavedMonthly: 8400, rating: 4.8, ratingCount: 124, setupMinutes: 15,
    requirements: ["Shopify", "Klaviyo / Postscript"],
    steps: ["Detects abandoned cart", "Hour 1: empathy email", "Hour 24: free shipping offer", "Hour 72: last-chance discount"],
    featured: true, source: "Zapier", sourceUrl: "https://zapier.com", priceModel: "freemium",
  }),
  wf({
    slug: "review-request-automation", roleSlug: "ecommerce-owner",
    name: "Request reviews 14 days after delivery automatically",
    tagline: "Get UGC and reviews on autopilot.",
    description: "Sends review + photo requests 14 days after delivery to capture authentic UGC.",
    category: "Marketing",
    timePerAction: "Saves 1.5 min per request",
    hoursSavedWeekly: 4, dollarsSavedMonthly: 3200, rating: 4.7, ratingCount: 89, setupMinutes: 12,
    requirements: ["Shopify", "Yotpo / Loox"],
    steps: ["Tracks delivery confirmation", "14-day delay", "Requests review + photos", "Auto-features 5-stars"],
    source: "Zapier", sourceUrl: "https://zapier.com", priceModel: "freemium",
  }),
  wf({
    slug: "customer-segmentation", roleSlug: "ecommerce-owner",
    name: "Auto-segment customers by behavior weekly",
    tagline: "VIPs, churners, and one-timers — categorized.",
    description: "Auto-classifies customers into VIP / Repeat / At-risk / Churned cohorts. Triggers tailored campaigns.",
    category: "Marketing",
    timePerAction: "Saves 12 min per segmentation update",
    hoursSavedWeekly: 3, dollarsSavedMonthly: 5200, rating: 4.7, ratingCount: 41, setupMinutes: 20,
    requirements: ["Shopify", "Klaviyo"],
    steps: ["Pulls order history weekly", "Classifies by RFM", "Updates Klaviyo segments", "Triggers cohort campaigns"],
    source: "Monican", priceModel: "monican-setup",
  }),
  wf({
    slug: "product-question-bot", roleSlug: "ecommerce-owner",
    name: "Answer pre-purchase product questions in under 60 seconds",
    tagline: "Convert browsers who would've bounced.",
    description: "Sits on your product pages. Answers customer questions about sizing, materials, shipping with Claude-powered responses.",
    category: "Sales",
    timePerAction: "Saves 4 min per question",
    hoursSavedWeekly: 5, dollarsSavedMonthly: 6800, rating: 4.7, ratingCount: 67, setupMinutes: 15,
    requirements: ["Shopify", "Intercom / Crisp"],
    steps: ["Loads on product pages", "Reads product details + FAQ", "Answers buyer questions", "Escalates if uncertain"],
    source: "Monican", priceModel: "monican-setup",
  }),
];

// Helpers
export function getIndustryBySlug(slug: string): Industry | undefined {
  return INDUSTRIES.find((i) => i.slug === slug);
}

export function getRoleBySlug(slug: string): Role | undefined {
  return ROLES.find((r) => r.slug === slug);
}

export function getRolesByIndustry(industrySlug: string): Role[] {
  return ROLES.filter((r) => r.industrySlug === industrySlug);
}

export function getWorkflowsForRole(roleSlug: string): Workflow[] {
  return WORKFLOWS.filter((w) => w.roleSlug === roleSlug);
}

export function getWorkflow(roleSlug: string, workflowSlug: string): Workflow | undefined {
  return WORKFLOWS.find((w) => w.roleSlug === roleSlug && w.slug === workflowSlug);
}
